src/components/landing/pages/intro/intro.tsx
=> changed the intro page when logged in

public/config, public/locales/de.json, public/locales/en.json, public/me, src/api/user.ts, src/components/initialize/initialize-user-state-from-api.tsx, src/components/landing/pages/login/auth/via-email.tsx
worked on the email sign in process
=> Email sign in

README.md, package.json
=> renamed repo to react client

src/utils/apiUtils.ts
=> Fix json decode in getMe

src/components/landing/pages/history/history.tsx
convert the old localStorage["notehistory"] to the new history format, if there is no new history in localStorage
fixes #20
=> convert the old history from localStorage

src/utils/historyUtils.ts
=> fix check for string exist

src/components/landing/pages/login/auth/via-ldap.tsx
=> fixed controlId in via-ldap

src/components/landing/pages/login/auth/via-one-click.tsx, src/initializers/fontAwesome.ts
=> changed oauth icon to fa-address-book

src/components/element-separator/element-separator.tsx
This PR adds a component, which can place an react element between its children.
=> Add element-separator

src/components/landing/layout/index.tsx
=> fix routing of "/"

src/components/landing/pages/intro/intro.tsx
=> added translation for or

src/api/config.ts
=> Remove backend url from frontend config api call

src/initializers/index.ts
=> Add custom loading screen delay

public/index.html, src/components/landing/layout/style/index.scss
=> Use bootstrap class for background color

src/components/landing/layout/footer/language-picker.scss, src/components/landing/layout/footer/language-picker.tsx
=> changed language-picker select to react bootstraps version

public/locales/en.json, src/components/landing/pages/history/history-table/history-table-row.tsx, src/components/landing/pages/history/history-table/history-table.tsx
=> Add tags to history table

src/api/config.ts, src/api/user.ts, src/components/application-loader/application-loader.tsx, src/components/landing/pages/login/auth/via-email.tsx, src/components/landing/pages/login/auth/via-ldap.tsx, src/components/landing/pages/login/auth/via-open id.tsx, src/utils/apiUtils.ts
Replace Promise then chains with async / await
=> use async and await

src/api/user.ts
=> all auth provider should work via `/auth/`

src/components/application-loader/application-loader.tsx, src/components/application-loader/loading-screen.tsx
=> Extract loading screen compontent

src/initializers/configLoader.ts, src/initializers/i18n.ts
=> convert more promise chains to async await

LICENSE, package.json
This PR adds the [AGPL 3.0](https://www.gnu.org/licenses/agpl-3.0.de.html)
=> Add AGPL 3.0

src/components/application-loader/loading-screen.tsx, src/components/landing/layout/footer/powered-by-links.tsx, src/components/links/external-link.tsx, src/components/links/internal-link.tsx, src/components/links/translated-external-link.tsx, src/components/links/translated-internal-link.tsx, src/components/links/types.ts
This PR fixes a bug in the InternalLinkComponents and restructures the types of the link components.
=> Restructure Link Components and fix internal link children error

src/components/editor/task-bar/dark-mode-button.tsx, src/initializers/fontAwesome.ts
see https://github.com/codimd/server/issues/378
=> change dark mode button to show sun icon if toggled

src/components/landing/layout/navigation/header-bar/header-bar.tsx
This PR fixes the size of the "new note button". Fixes #101
=> Add flex to grow button

src/components/landing/pages/history/history-toolbar/clear-history-button.tsx
=> clear history modal now correctly closes

src/components/landing/pages/login/auth/social-link-button/social-link-button.scss
This PR fixes a color bug in the social link button.
=> Fix text color when hovering social link buttons

src/components/landing/layout/navigation/header-bar/header-bar.tsx, src/components/landing/layout/navigation/sign-in-button.tsx, src/components/landing/pages/intro/cover-buttons/cover-buttons.tsx, src/components/landing/pages/login/login.tsx
This PR improves the sign in button by extending its props with the button props.
=> Improve sign in button

public/locales/en.json, src/components/landing/pages/history/history-toolbar/export-history-button.tsx, src/components/landing/pages/history/history-toolbar/history-toolbar.tsx, src/components/landing/pages/history/history-toolbar/import-history-button.scss, src/components/landing/pages/history/history-toolbar/import-history-button.tsx, src/components/landing/pages/history/history.tsx, src/utils/historyUtils.ts
=> finished history toolbar buttons

src/components/common/show-if.tsx
This component makes it easier to show a dom only if a condition is true.
=> Add show-if component

README.md
This PR adds some more necessary steps to the README
=> Add examples and cd command to README

src/components/landing/pages/history/history-table/history-table.scss, src/components/landing/pages/history/history-table/history-table.tsx
This PR sets fixed sizes for the history table columns.
=> Add fixed sizes for history table columns

.github/workflows/build.yml
This PR restructures the github action flow, so it doesn't use an external action.
=> Restructure github flow

src/utils/apiUtils.ts
This PR fixes the behaviour of "expectResponseCode"
=> Throw error if unexpected response code

src/components/application-loader/loading-screen.tsx, src/components/editor/editor.tsx, src/components/element-separator/element-separator.tsx, src/components/landing/layout/version-info/version-info.tsx, src/components/landing/pages/login/login.tsx, src/components/landing/pages/profile/profile.tsx, src/components/links/external-link.tsx, src/components/links/internal-link.tsx, src/components/pagination/pager-pagination.tsx
This PR replaces all occurances of `condition ? component : null` with `<ShowIf>`
=> Use more show-if

public/locales/en.json, src/components/editor/editor-window/editor-window.tsx
This PR adds a new translation key for the editor text placeholder.
Fixes #188
=> Add placeholder translation

src/components/application-loader/application-loader.scss, src/components/application-loader/loading-screen.tsx
This PR fixes the position of the icon in the application loader
=> Fix icon position in application loading screen

public/api/v2/notes/old, src/api/note.ts, src/components/error/not-found.tsx, src/components/redirector/redirector.tsx, src/index.tsx
it will redirect every request to /$something that is not handled otherwise (/intro, /login and such) to /n/$something
=> added redirector component

package.json, src/components/common/split-divider/split-divider.scss, src/components/common/split-divider/split-divider.tsx, src/components/common/splitter/splitter.scss, src/components/common/splitter/splitter.tsx, src/components/editor/editor.tsx, src/components/editor/markdown-preview/markdown-preview.tsx, src/components/editor/task-bar/editor-view-mode.tsx, yarn.lock
This PR adds a working split component
=> Add editor split component

src/components/landing/pages/history/common/entry-menu.scss, src/components/landing/pages/history/common/entry-menu.tsx
This PR redesigns the context menu button on the history page
=> Redesign history context button

.idea/dictionaries/codimd.xml, .idea/dictionaries/tilman.xml
JetBrains-IDE-Settings
This PR adds the words "codimd" and "CodiMD" to the jetbrains dictionary
=> Add codimd to jetbrains dictionary

CHANGELOG.md
CHANGELOG.md
This PR adds a missing change log entry about twemoji.
=> Add twemoji to changelog

src/components/editor/editor.tsx, src/components/editor/markdown-preview/markdown-preview.tsx, src/components/editor/markdown-preview/regex-plugins/replace-pdf-short-code.ts, src/components/editor/markdown-preview/replace-components/pdf/pdf-frame.scss, src/components/editor/markdown-preview/replace-components/pdf/pdf-frame.tsx
The markdown rendering component
This PR adds embedding of pdf links via `{%pdf LINK %}`
=> PDF embedding

src/components/editor/editor-window/editor-window.scss
The editor
This PR increases the font size in the editor.
=> Change font settings in editor

src/components/editor/editor.tsx, src/components/editor/markdown-preview/markdown-preview.tsx, src/components/editor/markdown-preview/replace-components/gist/gist-frame.tsx, src/components/editor/markdown-preview/replace-components/vimeo/vimeo-frame.tsx, src/components/editor/markdown-preview/replace-components/youtube/youtube-frame.tsx
The markdown rendering component
This PR improves the code quality of `markdown-preview.tsx` by deduplicating some code blocks that are used to identify which function should replace a tag.
=> Deduplicate code

src/components/editor/markdown-renderer/markdown-renderer.tsx
This PR adds a sub node renderer function for the component replacer. With this function they can convert their children, if they're e.g. altering the dom structure but want to keep the children.
=> Add subnode renderer

src/components/landing/layout/footer/language-picker.tsx
Language picker
This PR extracts the supported languages into an array
=> Extract language codes into object

src/components/common/highlighted-code/highlighted-code.tsx
add uniqe key to highlight line numbers
=> Add unique key

CHANGELOG.md, src/components/common/highlighted-code/highlighted-code.scss, src/components/common/highlighted-code/highlighted-code.tsx, src/components/editor/markdown-renderer/markdown-it-plugins/highlighted-code.ts, src/components/editor/markdown-renderer/markdown-renderer.tsx, src/components/editor/markdown-renderer/replace-components/highlighted-code/highlighted-code.scss, src/components/editor/markdown-renderer/replace-components/highlighted-fence/highlighted-fence.tsx
The code block highlighter
This PR adds line wrapping for the code block highlighter
#255
=> Restructure highlight code to enable line wrapping 

src/components/editor/markdown-renderer/replace-components/one-click-frame/one-click-embedding.tsx, src/components/editor/markdown-renderer/replace-components/pdf/pdf-frame.tsx
The pdf one click embedding
This PR adds a new callback to the one click embedding and uses it in the pdf embedding
=> Change pdf embedding size when clicked

src/components/common/branding/branding.tsx
The branding component
This PR removes a console log and fixes a null check
=> Remove log message and fix null check

src/components/editor/markdown-renderer/replace-components/asciinema/asciinema-replacer.tsx
This PR adds key prop to the AsciinemaFrame in the AsciinemaReplacer
=> Add key prop to asciinema replacer

src/components/editor/editor-window/editor-window.scss
Editor
This PR adds twemoji to the font family of the editor
=> Use twemoji in editor

src/components/editor/editor.tsx, src/components/editor/editorTestContent.ts
Editor
This PR moves the editor default content (that is only needed for dev right now) into a separate file to reduce the length of editor.tsx
=> Move editor test content into separate file

src/components/common/splitter/splitter.tsx, src/components/editor/markdown-toc/markdown-toc.scss, src/components/editor/renderer-window/markdown-render-window.tsx, src/global-style/index.scss
The editor css
This PR improves the editor css in preparation for the sync scroll.
#212
=> Improve css in preparation for the sync scroll

src/components/editor/markdown-renderer/replace-components/image/image-replacer.tsx
The markdown renderer
This PR adds a key to the ImageReplacer.
=> Add key to image replacer

src/components/editor/markdown-renderer/markdown-renderer.tsx
The markdown renderer
This PR disables the markdown it debug console output for production builds.
=> Disable markdown it debug output in production

package.json, yarn.lock
package.json
This PR updates react-scripts
=> updated react-scripts

cypress/integration/toolbar.spec.ts, src/components/editor/editor-window/tool-bar/utils.test.ts, src/components/editor/editor-window/tool-bar/utils.ts
changed addTable function
e2e tests
This PR adds end2end tests for the toolbar
=> added toolbar e2e test

.github/workflows/build.yml, .github/workflows/e2e.yml
Github actions workflow
This PR fixes the github action workflows to work with the new main branch.
=> change github action workflows to main

.editorconfig, public/locales/ar.json, public/locales/en.json, public/locales/pt.json
The translation json files
This PR changes the json identation to 4 spaces and reformats the translation json files.
=> Change indentation for json files to 4 spaces and reformat json files

cypress/integration/history.spec.ts
end2end test
This PR enhances the history end2end test
=> enhanced the e2e history.spec

src/components/editor/document-renderer-pane/document-render-pane.tsx, src/components/editor/editor-pane/editor-pane.tsx, src/components/editor/editor.tsx, src/components/editor/markdown-renderer/markdown-it-plugins/line-number-marker.ts, src/components/editor/scroll/scroll-props.ts, src/components/editor/scroll/utils.ts, src/components/editor/splitter/splitter.tsx, src/components/editor/table-of-contents/table-of-contents.tsx, src/components/markdown-renderer/markdown-renderer.tsx, yarn.lock
Editor
This PR adds synchronous scrolling between the codemirror and the preview pane.
fixes #212
=> Synchronous scrolling

src/components/editor/editor.tsx, src/components/editor/shortcut/shortcut.ts
editor
This PR adds shortcuts to the viewmode.
fixes #366
=> added viewMode shortcuts

src/components/editor/document-renderer-pane/document-render-pane.tsx, src/components/editor/editor-pane/editor-pane.tsx
Editor
This PR:
- fixes a crash bug
- fixes a jump bug
=> Fix scroll bugs

src/components/editor/app-bar/help-button/shortcuts.tsx
Shortcut dialog
This PR adds a key prop to the shortcut list items
=> Add key prop to shortcut listgroup

src/components/editor/app-bar/help-button/shortcuts.tsx, src/components/editor/shortcut/shortcut.ts
shorcuts
This PR fixes shortcuts for macs.
=> fixed shortcuts for macs

.github/workflows/build.yml, README.md
This PR dropes the node 10 test, because of #497
=> Drop node 10 test

package.json, public/locales/en.json, src/components/editor/editorTestContent.ts, src/components/markdown-renderer/markdown-renderer.tsx, src/components/markdown-renderer/replace-components/flow/flowchart-replacer.tsx, src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx, src/external-types/flowchart.js/index.d.ts, yarn.lock
editor
This PR readds flowchart.js diagrams
closes #502
=> Added flowchart diagrams

src/components/markdown-renderer/replace-components/image/image-frame.tsx, src/components/markdown-renderer/replace-components/image/image-replacer.tsx
This PR adds the title attribute to images.
fixes #518
=> added title attribute to images

src/components/markdown-renderer/markdown-renderer.tsx, src/components/markdown-renderer/replace-components/task-list/task-list-replacer.tsx, yarn.lock
Clickable todos
This PR fixes some issues I found in the clickable-todo-code AFTER merging the code :sweat_smile:
=> adjust some review suggestions

.gitignore, src/components/markdown-renderer/replace-components/linemarker/linemarker-replacer.tsx
This PR fixes a bug that was caused by missed code in #434
=> Renamed missed code

src/components/markdown-renderer/renderer-utils.tsx, src/components/markdown-renderer/replace-components/ComponentReplacer.ts, src/components/markdown-renderer/replace-components/abc/abc-replacer.tsx, src/components/markdown-renderer/replace-components/asciinema/asciinema-replacer.tsx, src/components/markdown-renderer/replace-components/csv/csv-replacer.tsx, src/components/markdown-renderer/replace-components/flow/flowchart-replacer.tsx, src/components/markdown-renderer/replace-components/gist/gist-replacer.tsx, src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-fence-replacer.tsx, src/components/markdown-renderer/replace-components/image/image-replacer.tsx, src/components/markdown-renderer/replace-components/katex/katex-replacer.tsx, src/components/markdown-renderer/replace-components/linemarker/linemarker-replacer.tsx, src/components/markdown-renderer/replace-components/mermaid/mermaid-replacer.tsx, src/components/markdown-renderer/replace-components/pdf/pdf-replacer.tsx, src/components/markdown-renderer/replace-components/possible-wider/possible-wider-replacer.tsx, src/components/markdown-renderer/replace-components/quote-options/quote-options-replacer.tsx, src/components/markdown-renderer/replace-components/sequence-diagram/sequence-diagram-replacer.tsx, src/components/markdown-renderer/replace-components/task-list/task-list-replacer.tsx, src/components/markdown-renderer/replace-components/vimeo/vimeo-replacer.tsx, src/components/markdown-renderer/replace-components/youtube/youtube-replacer.tsx, yarn.lock
This PR changes the replacer API so you don't have to add the react key yourself.
=> Remove keys from replacers

src/components/error-boundary/error-boundary.tsx, src/index.tsx
the whole app
This PR adds an error boundary
fixes #526
=> added error boundary

src/components/editor/editor-pane/editor-pane.tsx, src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preferences.tsx, src/components/editor/editor-pane/tool-bar/tool-bar.tsx, src/redux/editor/methods.ts, src/redux/editor/reducers.ts, src/redux/editor/types.ts
Editor -> editor config
This PR is a re-do of #541 as that got accidentally overwritten prior merging.
#541
=> Re-do broken PR #541

package.json, yarn.lock
This PR adds a missing type dependency.
=> add @types/domhandler

CHANGELOG.md, package.json, public/locales/en.json, src/components/editor/editorTestContent.ts, src/components/markdown-renderer/full-markdown-renderer.tsx, src/components/markdown-renderer/markdown-it-plugins/highlighted-code.ts, src/components/markdown-renderer/replace-components/vega-lite/vega-chart.tsx, src/components/markdown-renderer/replace-components/vega-lite/vega-replacer.tsx, yarn.lock
editor -> render
This PR adds vega-lite diagrams
#573
=> add vega-lite diagram

src/components/markdown-renderer/replace-components/image/frame.tsx
This PR removes an unused prop in the ImageFrame
=> Remove unused prop

cypress/integration/link.spec.ts, src/components/editor/app-bar/help-button/links.tsx, src/components/error-boundary/error-boundary.tsx, src/components/landing-layout/footer/social-links.tsx, src/links.json
Overall links.json file (help dialog, footer)
Following to the discussion in codimd/server#496, this commit changes element.io links to matrix.to in the new react-client as well.
codimd/server#496
=> Change element.io links to matrix.to links

src/components/editor/document-renderer-pane/document-render-pane.tsx
This PR fixes the scrolling in multi-line-blocks.
=> Fix render pane scrolling

src/components/markdown-renderer/basic-markdown-renderer.tsx, src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx
This PR fixes the wasm loader in firefox
=> Set wasmfolder

src/components/markdown-renderer/replace-components/vega-lite/vega-chart.tsx
This PR removes the empty error message
=> Use right clear error

src/components/editor/document-bar/menus/export-menu.tsx, src/components/editor/document-bar/menus/import-menu.tsx
document bar
This PR adds 'gitlab snippet' item to import and export menus
=> adds 'gitlab snippet' item to import and export menus

cypress/integration/export.spec.ts, src/components/common/download/download.ts, src/components/editor/document-bar/document-bar.tsx, src/components/editor/document-bar/menus/export-menu.tsx, src/components/editor/document-bar/menus/export/markdown.tsx
editor
This PR adds a markdown export
partly #623
=> added markdown export

public/locales/en.json, src/components/common/lock-button/lock-button.tsx, src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
markmap render
This PR makes it possible to deactivate mouse inputs.
fixes #651
=> Markmap make mouse input toggle

src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
markmap fram
This PR add the correct css import
=> added missing button-inside css file in MarkmapFrame

src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
Flowchart
This PR fixes the font color in the flowchart diagrams in dark mode.
=> Fix font-color in flowchart

src/components/editor/editor.tsx, src/components/editor/hooks/useFirstDraw.ts
Editor
This PR extracts the code that indicates if this is a first draw into a hook.
=> extract code into useFirstDraw hook

src/components/editor/document-renderer-pane/scrolling-document-render-pane.tsx, src/components/editor/scroll/hooks/use-scroll-to-line-mark.ts, src/components/editor/scroll/hooks/use-user-scroll.ts
Document pane
This PR extracts some code into hooks that handles scroll syncing.
=> extract scroll code from renderer into hook

cypress/integration/code.spec.ts, cypress/integration/helpDialog.spec.ts, src/components/markdown-renderer/markdown-it-configurator/BasicMarkdownItConfigurator.tsx, src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx, yarn.lock
This PR fixed #721.
fixes #721
=> move taskLists from full to basic renderer

package.json, src/components/editor/editor-pane/autocompletion/emoji.ts, src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx, yarn.lock
Emoji picker
This PR improves the emoji picker code by splitting effects.
https://github.com/nolanlawson/emoji-picker-element/pull/61
=> Refactor emoji code

cypress/integration/history.spec.ts, package.json
cypress tests
This PR fixes the cypress tests, by adding a stub to the put request.
=> fix cypress runs

.github/workflows/e2e.yml
cypress e2e tests
This PR adds screenshots as artifacts to the e2e workflow.
This should be useful the next time something goes wrong with cypress…
=> added screenshots artifacts in e2e workflow

CHANGELOG.md
The changelog
This PR added remove notices of HTML import from url or file to the changelog.
fixes #722
=> added remove notices to changelog

.github/workflows/reuse.yml
github workflows
This PR renames the job in the reuse workflow to reuse.
~~After this PR is merged, the settings of the repo need to be changed~~
As I'm now able to do this myself, I did it already
=> renamed reuse workflow job name to reuse

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question---other.md, .github/pull_request_template.md, .reuse/dep5
PR and Issue templates
This PR fixes PR and Issue templates
=> fixed issues and pr templates

public/api/v2/config
config API mock
This PR fixes the config file to point to the moved acme.png
=> fixed config to point to correct acme.png

public/api/v2/me, public/api/v2/users/dermolly, public/api/v2/users/emcrx, public/api/v2/users/mrdrogdrog, src/components/editor/document-bar/connection-indicator/connection-indicator.tsx, src/components/editor/document-bar/document-info/document-info-button.tsx, src/components/editor/document-bar/permissions/permission-modal.tsx, src/components/pad-view-only/document-infobar.tsx
multiple
This PR fixes the url of avatar.png as it was moved in #782.
=> fixed avatar url as we moved it in the reuse pr

.github/workflows/reuse.yml
This PR fixes when the reuse workflow runs. Now it should run the exact same time all other workflows run.
=> changed when the reuse workflow runs to mimic all other workflows

CHANGELOG.md, cypress/integration/toolbar.spec.ts, public/locales/en.json, src/components/common/number-range/number-range.ts, src/components/editor/editor-pane/tool-bar/table-picker/custom-table-size-modal.tsx, src/components/editor/editor-pane/tool-bar/table-picker/table-picker-button.tsx, src/components/editor/editor-pane/tool-bar/table-picker/table-picker-dialog.tsx, src/components/editor/editor-pane/tool-bar/table-picker/table-picker.scss, src/components/editor/editor-pane/tool-bar/table-picker/table-picker.tsx, src/components/editor/editor-pane/tool-bar/tool-bar.tsx, src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.ts
This PR adds an overlay to create tables in different sizes
fixes #761
=> added table overlay to table toolbar button.

cypress.json, cypress/integration/history.spec.ts, cypress/integration/profile.spec.ts, cypress/support/config.ts, src/components/history-page/history-page.tsx
e2e tests
This PR changes all cy.route calls to cy.intercept
fixes #805
=> changed calls to cy.route to cy.intercept

renovate.json
Same as https://github.com/hedgedoc/react-client/pull/811 but without renovate which deletes my branch
=> Change renovate label to "type: maintenance"

src/components/editor/editor-pane/tool-bar/table-picker/table-picker.tsx
table picker
This PR fixes table-picker.tsx. It adds missing key props
=> fixed table-picker.tsx

cypress/integration/upload.spec.ts, src/components/editor/editor-pane/editor-pane.tsx
e.g markdown editor
This PR fixes pasting text.
Fixes #870
=> fix pasting text

cypress/support/config.ts, public/api/v2/config, src/components/editor/app-bar/dark-mode-button.tsx, src/components/editor/app-bar/navbar-branding.tsx, src/components/editor/document-bar/revisions/revision-modal.tsx, src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx, src/components/editor/table-of-contents/table-of-contents.scss, src/components/markdown-renderer/replace-components/abc/abc-frame.tsx, src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx, src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx, src/components/markdown-renderer/replace-components/image/image-frame.tsx, src/components/markdown-renderer/replace-components/image/lightboxedImageFrame.tsx, src/hooks/common/use-apply-dark-mode.ts, src/hooks/common/use-is-dark-mode-activated.ts, src/style/index.scss
All over the place
This PR
- adds a dark mode hook
- Add scrollable overflow for abcjs and graphviz images
- replace links
- Caps the max height of the toc overlay
=> Minor fixes

.reuse/dep5
Locales
This PR relicenses the locales under CC-BY-SA 4.0, because AGPL is a code license.
=> Relicense locales under CC-BY-SA

src/components/editor/editorTestContent.ts
Editor demo content
This PR changes the tags in the demo content from the old syntax to a yaml array.
=> Use yaml-array in demo content

src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.test.ts
toolbarButtonUtils test
This PR fixes the disabled toolbarButtonUtils test
=> fixed toolbarButtonUtils.test.ts

renovate.json
Renovate
This PR activates a renovate feature that regenerates the lock file every week.
=> Activate "maintainLockFilesWeekly" in renovate config

README.md
README
This PR fixes production mode instructions in README.md
=> README: Fix production mode instructions

src/components/editor-page/editor-page.tsx, src/components/editor-page/hooks/useEditorModeFromUrl.ts
Editor
This PR extracts a effect into its own hook.
=> Extract code into hook

src/components/editor-page/editor-page.tsx, src/components/editor-page/use-notification-test.tsx, src/components/landing-layout/landing-layout.tsx, src/components/notifications/notifications.scss, src/components/notifications/ui-notification-toast.tsx, src/components/notifications/ui-notifications.tsx, src/redux/index.ts, src/redux/ui-notifications/methods.ts, src/redux/ui-notifications/reducers.ts, src/redux/ui-notifications/types.ts, src/style/variables.light.scss
This PR adds dismissable, temporary notifications. Every notification can have actions to execute.
Closes #816
=> Notifications

LICENSE
Repository License
This PR adds a symlink to the main license that is used in the repo.
=> Add symlink for LICENSE

LICENSE
Repository
Symlinks are not recognized by GitHub. Therefore this PR changes the LICENSE symlink to a file.
=> Change type of LICENSE

renovate.json
renovate config
This PR adds  new renovate group for i18next
=> add new renovate group for i18next

.mailmap
Repository
I changed my used e-mail adress for git. This PR changes the mailmap file.
=> Change mailmap entry for "Tilman Vatteroth"

package.json, src/api/auth/index.ts, src/api/config/index.ts, src/api/history/index.ts, src/api/me/index.ts, src/api/media/index.ts, src/api/notes/index.ts, src/api/revisions/index.ts, src/api/tokens/index.ts, src/components/application-loader/initializers/fetch-and-set-banner.ts, src/components/application-loader/initializers/i18n.ts, src/components/application-loader/initializers/index.ts, src/components/intro-page/requests.ts, src/components/landing-layout/navigation/sign-in-button.tsx, src/components/profile-page/settings/profile-account-management.tsx, src/hooks/common/use-backend-base-url.ts, src/hooks/common/use-customize-assets-url.ts, src/hooks/common/use-frontend-base-url.ts
Link generation with URLs from environment variables
There was a problem with the link generation logic if you e.g. set "/" as backend url. This PR fixes this bug by requiring a "/" at the end of every base URL.
=> Change schema of url environment variables

src/external-types/reveal.js/index.d.ts
external types
This PR adds RevealOptions for reveal 4.1.0
=> Add RevealOptions for revealjs 4.1.0 

renovate.json
Renovate
This PR activates the renovate dependency dashboard
=> Activate renovate dependency dashboard

src/components/editor-page/editor-page.tsx, src/components/editor-page/editor-pane/editor-pane.tsx, src/components/editor-page/render-context/iframe-editor-to-renderer-communicator-context-provider.tsx, src/components/editor-page/render-context/iframe-renderer-to-editor-communicator-context-provider.tsx, src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts, src/components/editor-page/renderer-pane/render-iframe.tsx, src/components/intro-page/intro-page.tsx, src/components/render-page/hooks/use-image-click-handler.ts, src/components/render-page/iframe-markdown-renderer.tsx, src/components/render-page/render-page.tsx
Iframe communicator
This PR extracts some rendering code and introduces a new context provider for the renderer to editor communicator.
=> Iframe communicator context (2/3)

.github/workflows/e2e.yml, public/locales/en.json, src/components/editor-page/editor-pane/autocompletion/code-block.ts, src/components/editor-page/editor-pane/autocompletion/header.ts, src/components/editor-page/editor-pane/autocompletion/index.ts, src/components/notifications/ui-notification-toast.tsx
Cypress E2E CI Jobs
This PR fixes the stability and speed of the E2E job.
=> Improve stability and speed of E2E tests

.github/workflows/e2e.yml, cypress.json
This PR fixes/adds/improves/...
=> Parallel ci jobs

src/components/notifications/ui-notification-toast.tsx
Notifications
Fix unique key error in ui notification
=> Fix unique key in ui-notification-toast

.env.production, .env.production.license
CSP security
This PR disables the inline runtime chunk for more csp security.
=> Disable inline runtime chunk

src/components/common/routing/note-direct-link-redirector.tsx, src/components/editor-page/editor-pane/autocompletion/code-block.ts, src/components/editor-page/editor-pane/autocompletion/container.ts, src/components/markdown-renderer/replace-components/link-replacer/link-replacer.tsx, src/components/markdown-renderer/utils/html-react-transformer.tsx, src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts, src/index.tsx, src/redux/note-details/reducer.ts
Many
This PR fixes some flaws that were pointed out by https://lgtm.com/projects/g/hedgedoc/react-client/?mode=list
=> Fix security related problems

src/components/editor-page/editor-pane/editor-pane.tsx, src/components/editor-page/editor-pane/hooks/use-apply-scroll-state.ts, src/components/editor-page/editor-pane/hooks/use-code-mirror-options.ts, src/components/editor-page/editor-pane/hooks/use-on-editor-file-drop.ts, src/components/editor-page/editor-pane/hooks/use-on-editor-paste-callback.ts, src/components/editor-page/editor-pane/hooks/use-on-editor-scroll.ts
Code Mirror
This PR extracts some code into custom hooks.
=> Extract editor code into hooks

locales/en.json, src/components/markdown-renderer/replace-components/asciinema/asciinema-frame.tsx, src/components/markdown-renderer/replace-components/gist/gist-frame.tsx, src/components/markdown-renderer/replace-components/one-click-frame/one-click-embedding.tsx, src/components/markdown-renderer/replace-components/vimeo/vimeo-frame.tsx, src/components/markdown-renderer/replace-components/youtube/youtube-frame.tsx
OneClickEmbedding
This PR adds a target description to OneClickEmbedding
fixes #1582
=> feat: add a target description to OneClickEmbedding

cypress/integration/intro.spec.ts, cypress/integration/renderer-mode.spec.ts, cypress/support/get-iframe-content.ts, src/components/editor-page/renderer-pane/render-iframe.tsx, src/components/render-page/window-post-message-communicator/rendering-message.ts, src/utils/cypress-attribute.ts
Renderer type test
This PR fixes the renderer type test
=> Fix renderer type test

src/components/notifications/ui-notification-toast.tsx
Notifications
This PR swaps the custom usage of setInterval with the useInterval hook.
=> use useInterval hook in ui-notification-toast

cypress/integration/autocompletion.spec.ts, src/components/editor-page/editor-pane/editor-pane.tsx, src/components/editor-page/editor-pane/extended-codemirror/extended-codemirror.tsx
Editor autocompletion
This PR fixes the autocompletion rendering
=> Fix autocompletion

CHANGELOG.md
Changelog
This PR adds plantuml to the changelog and corrects the faq URL for the sequence diagram entry.
https://github.com/hedgedoc/react-client/issues/1712
=> Fix changelog faq

src/components/history-page/history-toolbar/tag-selection-input.tsx
history page
This PR sorts the tags for the tag picker alphabetically
fixes #1338
=> feat: sort tags alphabetically

.github/workflows/deploy-main.yml, .github/workflows/deploy-pr.yml
PR deployment
This PR adds a parameter that has been missing when [migrating to v1 of the deployment action](https://github.com/hedgedoc/react-client/pull/1884)
=> Add missing parameter for deployment action

netlify/deploy-main.sh, netlify/deploy-pr.sh
Netlify
The netlify deployment is broken and we don't know why. This PR adds an error output.
=> Add error handling for netlify deployment

src/components/editor-page/table-of-contents/build-react-dom-from-toc-ast.tsx, src/components/landing-layout/footer/language-picker.tsx, src/components/markdown-renderer/markdown-extension/blockquote/parse-blockquote-extra-tag.ts, src/components/markdown-renderer/markdown-extension/link-replacer/anchor-node-preprocessor.ts
General code
This PR replaces the use of "substr" with "slice" because "substr" is deprecated.
https://stackoverflow.com/questions/52640271/why-is-string-prototype-substr-deprecated
=> Replace substr with slice

src/components/common/fork-awesome/__snapshots__/fork-awesome-icon.test.tsx.snap, src/components/common/fork-awesome/__snapshots__/fork-awesome-stack.test.tsx.snap, src/components/common/fork-awesome/fork-awesome-icon.test.tsx, src/components/common/fork-awesome/fork-awesome-stack.test.tsx, src/components/common/icon-button/__snapshots__/icon-button.test.tsx.snap, src/components/common/icon-button/__snapshots__/translated-icon-button.test.tsx.snap, src/components/common/icon-button/icon-button.test.tsx, src/components/common/icon-button/icon-button.tsx, src/components/common/icon-button/translated-icon-button.test.tsx, src/components/common/links/__snapshots__/external-link.test.tsx.snap, src/components/common/links/__snapshots__/internal-link.test.tsx.snap, src/components/common/links/__snapshots__/translated-external-link.test.tsx.snap, src/components/common/links/__snapshots__/translated-internal-link.test.tsx.snap, src/components/common/links/external-link.test.tsx, src/components/common/links/internal-link.test.tsx, src/components/common/links/translated-external-link.test.tsx, src/components/common/links/translated-internal-link.test.tsx, src/components/common/show-if/__snapshots__/show-if.test.tsx.snap, src/components/common/show-if/show-if.test.tsx, src/components/common/user-avatar/__snapshots__/user-avatar.test.tsx.snap, src/components/common/user-avatar/user-avatar.test.tsx
component test
This PR adds tests for common components
#2065
=> test: common components

src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap, src/components/editor-page/splitter/splitter.test.tsx, src/components/editor-page/splitter/splitter.tsx
Splitter component
This PR fixes types in the splitter component and the tests.
=> Fix splitter tests

.github/workflows/deploy-main.yml, .github/workflows/deploy-pr.yml, netlify/deploy-main.sh, netlify/deploy-pr.sh, netlify/netlify-cli.sh, netlify/patch-files.sh, package.json
Netlify-Deployment
Due to a bug in the netlify-cli script the commands won't be executed.
=> Fix parameters in netlify cli script

global-styles/github-markdown.scss
Markdown stylesheet
This PR removes the roman numbers for listings.
Fixes #2238
=> Remove roman line numbers

src/components/editor-page/editor-pane/editor-pane.tsx, src/redux/editor/reducers.ts, src/redux/editor/types.ts
editor
This PR adds spell check.
#479
=> feat: add spell check

.github/workflows/deploy-main.yml, .github/workflows/deploy-pr.yml, netlify/patch-files.sh
Netlify deployment
This PR fixes the environment variables for the netlify deployment
=> Fix environment variable in netlify deployment

src/components/landing-layout/navigation/sign-in-button.tsx
Login button
This PR fixes the URL of the login button
Closes #2445
=> fix(login): Fix login button url

.github/workflows/deploy-pr.yml
Workflows
This PR fixes a syntax error in the deploy workflow
=> Fix deployment workflow

.github/workflows/e2e.yml, cypress/e2e/word-count.spec.ts, src/components/common/redirect.tsx, src/components/editor-page/app-bar/navbar-branding.tsx, src/components/editor-page/app-bar/read-only-mode-button.tsx, src/components/editor-page/app-bar/slide-mode-button.tsx, src/components/history-page/history-card/history-card.tsx, src/components/history-page/history-table/history-table-row.tsx, src/components/landing-layout/navigation/header-bar/header-nav-link.tsx, src/components/landing-layout/navigation/sign-in-button.tsx
CI and tests
This PR fixes multiple problems with the CI and tests. Check the commit messages.
=> Multiple fixes

.github/workflows/deploy-pr.yml, .github/workflows/e2e.yml, package.json, src/components/common/links/internal-link.tsx, src/components/common/redirect.tsx, src/components/editor-page/app-bar/navbar-branding.tsx, src/components/editor-page/app-bar/read-only-mode-button.tsx, src/components/editor-page/app-bar/slide-mode-button.tsx, src/components/history-page/history-card/history-card.tsx, src/components/history-page/history-table/history-table-row.tsx, src/components/landing-layout/navigation/header-bar/header-nav-link.tsx, src/components/landing-layout/navigation/sign-in-button.tsx, src/extensions/extra-integrations/graphviz/graphviz-frame.tsx, yarn.lock
CI
run e2e and deploy workflows from branch if non-fork
=> feat: run e2e and deploy workflows from branch if non-fork

src/components/common/modals/__snapshots__/common-modal.test.tsx.snap, src/components/common/modals/__snapshots__/deletion-moadal.test.tsx.snap, src/components/common/modals/common-modal.test.tsx, src/components/common/modals/common-modal.tsx, src/components/common/modals/deletion-moadal.test.tsx
common modals
This PR adds tests for the common modal components
#2065
=> test: common modals

src/components/common/motd-modal/motd-modal.test.tsx, src/components/editor-page/render-context/editor-to-renderer-communicator-context-provider.tsx, src/components/editor-page/render-context/renderer-to-editor-communicator-context-provider.tsx, src/components/editor-page/renderer-pane/render-iframe.tsx, src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts, src/extensions/extra-integrations/gist/replace-gist-link.ts, src/extensions/extra-integrations/vimeo/__snapshots__/vimeo-frame.test.tsx.snap, src/extensions/extra-integrations/vimeo/replace-vimeo-link.ts, src/extensions/extra-integrations/vimeo/vimeo-frame.test.tsx, src/extensions/extra-integrations/youtube/__snapshots__/youtube-frame.test.tsx.snap, src/extensions/extra-integrations/youtube/replace-youtube-link.test.ts, src/extensions/extra-integrations/youtube/replace-youtube-link.ts, src/extensions/extra-integrations/youtube/youtube-frame.test.tsx
Many components
This PR fixes some security problems issued by CodeQL.
=> fix: Solve codeql security issues
