hedgedoc/react-client

src/components/landing/pages/login/login.tsx
Logged-in users that access /login should be redirected to the /history page.
In a future PR we maybe want to redirect users to their previuos page.
=> Redirect logged-in users from /login to /history

src/components/landing/layout/navigation/user-dropdown/user-dropdown.tsx
Text is now aligned on the same indentation, icons are set with fixed-width.
=> Improved text-icon-layout of user-dropdown

src/components/landing/pages/history/history.tsx
The title on the history page was yet untranslated. This PR adds translation support for the title and sets a bottom-margin.
=> Fix title on history page not being translated

src/components/application-loader/application-loader.tsx
The application loader has a bug, that causes the loader to re-run the init tasks every time the path changes. This PR fixes this.
=> Make application loader only trigger once

package.json
Even if you don't use the dev-setup, you'll need all eslint-packages to run webpack.
=> Make eslint packages not dev only

src/components/landing/layout/version-info/version-info.tsx
The version info link was not migrated to the new locales.
=> Fixed wrong translation at versionInfo label

src/components/landing/layout/navigation/sign-in-button.tsx, src/components/landing/pages/intro/cover-buttons/cover-buttons.tsx, src/components/landing/pages/login/login.tsx
This PR fixes two login-provider related UI things:
- The login buttons showed up even if no auth-provider was enabled. They will now only be shown if at least one provider is enabled. This is ideal for "anonymous-only" instances and prevents from users seeing an empty login page.
- The "sign-in via"-box for one-click-providers showed up without content when no such providers were configured. This box will now be hidden if no one-click-providers were configured.
=> Show login-buttons and boxes only if providers are configured

src/components/landing/layout/footer/language-picker.tsx
The browser is sending the combined language Code `language-Area`, but our language file names don't contain the area.
This PR adds a function, that removes the Area from the provided language code.
Fixes #155
=> Add function for language code shortening

src/components/links/internal-link.tsx
internal links now use the Link component instead of the LinkContainer component, because the later is intended for use with react-bootstrap components and not for simple translated strings. This misuse made the Releases link in the footer of the landing page non-clickable in master…
=> fix internal link

renovate.json
Even if renovate only creates 1-2 pull requests per day, they start to become annoying. This pull requests changes the time slot of renovate actions to Saturdays.
=> Updated schedule of renovate

src/components/landing/landing-layout.tsx, src/components/landing/pages/intro/intro.tsx, src/global-style/index.scss
This PR changes the landing layout that sticks the footer at the bottom of the landing page.
=> Show footer always at the bottom

src/components/landing/pages/history/history-card/history-card.tsx, src/components/landing/pages/history/history-table/history-table-row.tsx
This PR adds Links to the cards and table rows of the recent notes history for accessing the actual note of the history entry.
This PR also includes a small fix for the improper display of the dropdown-toggle in the actions column of the history table-view.
Before merging this PR the code needs to be adjusted so that the dropdown-toggle and pin icon on the history cards become clickable again!
Fixes #202
=> Add links from recent note history entries to the actual note

CHANGELOG.md, src/CHANGELOG.md
it follows the purposed format from https://keepachangelog.com/en/1.0.0/
as discussed in #174
=> the changelog for this project

package.json, src/components/editor/markdown-preview/markdown-preview.tsx, src/external-types/markdown-it-footnote/index.d.ts, yarn.lock
This PR makes it possible to use footnotes
=> added support for markdown-it-footnote

src/components/editor/markdown-renderer/markdown-renderer.tsx
Markdown renderer of editor
This PR fixes the bug that only up to 2 levels of heading were shown in the generated ToC. It's a simple matter of configuration and now the behavior is like in 1.6 again.
Fixes #256
=> Fixed ToC only showing up to 2 levels instead of 3

package.json, src/components/editor/markdown-renderer/markdown-renderer.tsx, src/external-types/markdown-it-imsize/index.d.ts, src/external-types/markdown-it-imsize/interface.ts, yarn.lock
Markdown renderer of the editor
This PR adds support for the image resizing syntax: `![](https://dummyimage.com/96 =48x48)`.
Closes #259
=> Added image resizing support via markdown-it-imsize

src/components/editor/markdown-renderer/markdown-it-plugins/linkify-extra.ts, src/components/editor/markdown-renderer/markdown-renderer.tsx, src/external-types/markdown-it-linkify/index.d.ts
The markdown renderer
This PR reactivates linkify, but executes it at the end of the plugin pipeline
Closes #236
=> Add linkify

src/components/common/highlighted-code/highlighted-code.scss, src/components/common/highlighted-code/highlighted-code.tsx, src/components/editor/markdown-renderer/markdown-it-plugins/highlighted-code.ts, src/components/editor/markdown-renderer/replace-components/highlighted-fence/highlighted-fence-replacer.tsx
This PR adds "start with line number" and "continue line number" syntax to highlighted code blocks
Closes #251
=> Add new syntax to code highlightning

src/components/editor/markdown-renderer/markdown-it-plugins/highlighted-code.ts
Code block highlightning
This PR improves the code highlight regex by allowing spaces before the language name.
=> Add spaces to highlighted code regex

src/components/editor/markdown-renderer/markdown-renderer.tsx, src/components/editor/markdown-renderer/replace-components/image/image-frame.tsx, src/components/editor/markdown-renderer/replace-components/image/image-replacer.tsx
This PR replaces all <img>'s in the markdown-it output with an ImageFrame component. This enables us to implement image proxies and other per image customization in the future.
closes #264
=> added image-replacer

public/locales/en.json, src/components/editor/markdown-renderer/replace-components/one-click-frame/one-click-embedding.scss, src/components/editor/markdown-renderer/replace-components/one-click-frame/one-click-embedding.tsx, src/components/editor/markdown-renderer/replace-components/pdf/pdf-frame.tsx
This PR adds the possibility to add a text below the icon on the embedding preview.
none
=> Added click-to-load text for pdf embeddings and general option for texts on the embedding preview

src/components/editor/markdown-renderer/markdown-renderer.tsx, src/components/editor/markdown-renderer/replace-components/possible-wider/possible-wider-replacer.tsx
This PR fixes a bug that two p-tags were encapsulated inside each other with the same key.
This bug was introduced because the wider-possible-replacer replaced each element that was subject to be enlarged with a brand new p-surrounding. That surrounding got the key of the old (now inner) element and therefore casts a duplicate key exception.
This fix solves that problem by setting the 'wider-possible' class attribute directly on the selected tag instead of creating a surrounding.
none
=> Fixed bug that two p-tags were encapsulated inside each other

src/components/editor/markdown-renderer/markdown-renderer.scss
markdown render css
This PR changed a comment in `markdown-renderer.scss` to explain why the usage of `*` is necessary
see https://github.com/codimd/react-client/pull/271#pullrequestreview-437942115
=> clarified comment in renderer CSS

renovate.json
The renovate bot
As seen in multiple PRs that renovate raised today, the @testing-library/ packages are not bundled in the 'packages:jsTest' pre-defined group. As they aren't relevant to be separated, this PR changes the config of renovate to treat them as one big PR in the future.
=> Updated test-class matching rule of renovate

public/locales/en.json, src/components/landing/layout/navigation/user-dropdown/user-dropdown.tsx, src/components/landing/pages/intro/cover-buttons/cover-buttons.tsx, src/components/landing/pages/intro/feature-links.tsx
Links in the landing page
It was discussed and agreed that all notes should reside under the /n/ namespace in the future. Even if we want to redirect all pre-2.0-notes from the root namespace to the /n/ namespace, it might be better to set the internal links for the features page properly instead on relying on the redirect.
This PR therefore replaces each occurence of `/features` with `/n/features`.
none
=> Replace links to /features with /n/features

CHANGELOG.md, src/components/editor/editor.tsx, src/components/editor/markdown-renderer/markdown-renderer.tsx, src/components/editor/markdown-renderer/regex-plugins/replace-asciinema-link.ts, src/components/editor/markdown-renderer/replace-components/asciinema/asciinema-frame.tsx, src/components/editor/markdown-renderer/replace-components/asciinema/asciinema-replacer.tsx, src/components/editor/markdown-renderer/replace-components/possible-wider/possible-wider-replacer.tsx
Editor -> markdown renderer
This PR adds support for Asciinema embedding. Similar to YouTube, Vimeo or Gist it works by pasting the URL of an asciinema-video in a single line of the note.
Closes #322
=> Add Asciinema integration

.github/workflows/e2e.yml
GitHub Workflow for e2e tests
This PR changes the e2e task name. so that it uses the browser name instead of always "chrome"
=> Correct browser name in e2e workflow

.github/workflows/e2e.yml, cypress.json
E2E tests in headless firefox
This PR fixes the unstable behaviour of the firefox e2e execution by increasing the time to wait for results when executing a cypress command.
Closes #356
=> Fix firefox e2e runs

renovate.json
renovatebot configuration
This patch adds the ability to automatically merge PRs from renovate
bot for certain update types, such as package pinning or linter, types
and test-library packages.
=> Add automerge config to renovatebot

package.json, public/api/v2/config, src/api/config/types.ts, src/components/editor/editorTestContent.ts, src/components/editor/markdown-renderer/markdown-it-plugins/plantuml-error.scss, src/components/editor/markdown-renderer/markdown-it-plugins/plantuml-error.ts, src/components/editor/markdown-renderer/markdown-renderer.scss, src/components/editor/markdown-renderer/markdown-renderer.tsx, src/external-types/markdown-it-plantuml/index.d.ts, src/external-types/markdown-it-plantuml/interface.d.ts, src/redux/config/reducers.ts, yarn.lock
Add PlantUML rendering support.
Code block like
```plantuml
Bob -> Alice : hello
```
are rendered as PlantUML diagrams using a PlantUML server.
#324
=> Add plantuml support

src/components/editor/markdown-renderer/markdown-renderer.scss
If you write a very long line in the editor, that can't be wrapped, because it's one word, then the renderer's width will grow too much.
This PR allow breaking of words in the renderer.
=> Allow word break in renderer

src/components/editor/editor-window/tool-bar/utils.test.ts, src/components/editor/editor-window/tool-bar/utils.ts
The emoji picker
This PR changes the emoji picker behaviour. It should insert the short code (`:+1:`) instead of the unicode symbol (:+1:)
=> Insert short code instead of native emoji

src/components/editor/markdown-renderer/markdown-renderer.tsx, src/external-types/markdown-it-emoji/index.d.ts, src/external-types/markdown-it-emoji/interface.d.ts
The markdown renderer
This PR adds a twemoji definition for markdown-it-emoji. It uses the definition from the emoji picker and translates it into the format, that markdown-it-emoji wants.
Fixes #385
=> Use twitter emojis for markdown-it-emoji

public/locales/en.json, src/components/editor/document-bar/export-menu.tsx
the editor menu
This PR added pdf export unavailability notice with link to FAQ.
As many users ask all the time why this was removed and when they'll get it back, this seemed like a fine solution in the meantime.
#401
=> pdf export unavailability notice

package.json, yarn.lock
dependencies
This PR removes start-server-and-test as it is no longer used. We're now using the cypress github action which handles this itself.
=> removed the unused dependency start-server-and-test

cypress.json
CI -> end to end tests (cypress)
While running tests, cypress records videos of each one and processes them afterwards. This needs some resources we could save to reduce the CI runtime as we don't use or upload these videos.
This PR disables the video recording of cypress.
none
=> Disable videos in cypress CI config

.github/workflows/e2e.yml, cypress.json, package.json, yarn.lock
The e2e tests
This PR changes the e2e workflow. It now uses the prod build, because that is what we actually want to test. It could also fix the firefox timeout.
=> Use prod build for e2e tests

src/components/editor/document-bar/menus/export-menu.tsx
editor / document bar
This PR fixes the "PDF does not work. Why?" link in export menu and also opens a new tab.
=> fix "PDF does not work. Why?" link

src/components/editor/editor-pane/editor-pane.scss, src/components/editor/editor-pane/tool-bar/tool-bar.tsx
Editor toolbar
This PR reduces the space between the editor toolbar buttons
Before:
After:
=> Reduce space between editor toolbar buttons

src/components/editor/editor.tsx, src/components/editor/shortcut/shortcut.ts
Editor -> Shortcuts
This fix needs a little bit of explanation. Normally the 'keyUp' prevent is preferred because it fires after being sure, that not some buttons more belong to the shortcut. Additionally, some platforms set the key-property of the 'keyDown'-event to the composition result of the key-combination thus resolving under certain environments to '€' while in other environments to 'e'.
The browser's event flow is as following: keyDown -> keyPress -> textInput -> keyUp.
As the keyUp-event is too late (after textinput) and the keyPress-event does not work properly with the modifiers, we felt compelled to use 'keyDown' and watch for 'e' as well as '€' key-properties. If some other keyboard locale does output different characters than these two, that person got a problem - meaning …
=> Fix editor being filled with €-symbols when pressing the editor-mode-shortcut on certain platforms

package.json, yarn.lock
This PR removes @types/react-bootstrap, because react-bootstrap ships it's own types now.
=> Remove @types/react-bootstrap

cypress/integration/autocompletion.spec.ts
auto completion e2e test
This PR improves the auto completion e2e test by checking if the title attribute is set for images.
fixes #522
=> check that the title attribute is set for images

src/components/editor/editor-pane/tool-bar/tool-bar.scss, src/components/editor/editor-pane/tool-bar/tool-bar.tsx
Editor -> Toolbar
The use of extra divider elements is not needed as we can set the css-after pseudo-class to the button groups with the same styling.
This way we can reduce the amount of elements in the DOM by a hand full.
none
=> Replace editor toolbar dividers with css pseudo-selector

src/components/editor/app-bar/help-button/cheatsheet.tsx
This PR fixes the code highlightning in the cheatsheet modal.
=> Add markdown body to cheatsheet

cypress/integration/maxLength.spec.ts, cypress/support/config.ts, cypress/support/index.ts, cypress/tsconfig.json, package.json, public/api/v2/config, public/locales/en.json, src/api/config/types.d.ts, src/components/editor/editor-modals/max-length-warning-modal.tsx, src/components/editor/editor-pane/editor-pane.tsx, src/components/editor/editor-pane/status-bar/status-bar.tsx, src/components/markdown-renderer/markdown-renderer.tsx, src/redux/config/reducers.ts, yarn.lock
Editor
This PR adds support for setting a maximal document length and showing warning modals and information if the note is longer than the limit.
=> Show warning if note is longer than configured maximum length

src/components/editor/editorTestContent.ts
Editor -> Test content
This PR replaces the word MathJax with KaTeX in our test content as we don't use MathJax anymore for processing the formulas.
#497
=> Replace MathJax with KaTeX in our test note-content

cypress/integration/link.spec.ts, src/components/editor/app-bar/help-button/links.tsx, src/components/editor/document-bar/menus/export-menu.tsx, src/components/error-boundary/error-boundary.tsx, src/components/landing-layout/footer/powered-by-links.tsx, src/components/landing-layout/footer/social-links.tsx, src/components/markdown-renderer/replace-components/sequence-diagram/deprecation-warning.tsx, src/links.json
Intro page -> Footer links, Error page link
This PR extracts static URLs throughout the application into an extra file for easier changes in the future. It also changes the former riot.im link to the new app.element.io link for our chat room.
codimd/server#495
=> Extract URLs in extra file and change riot link to element-link

public/locales/en.json, src/components/editor/table-of-contents/table-of-contents.tsx
Document render pane -> Toc button
This PR adds an info-message when clicking the ToC-button on a document without headings.
none
=> Add info message on empty toc

src/components/common/links/types.d.ts
Internal
This PR removes unnecessary export of GeneralLinkProp.
export
=> removed unnecessary export of GeneralLinkProp

README.md, craco.config.js, package.json, yarn.lock
craco config, package.json-scripts
This PR adds webpack-bundle-analyzer altogether with a new yarn command: `yarn analyze` to generate a static analysis report as `build/report.html`.
none, maybe #1
=> Add webpack-bundle-analyzer as dev-tool

src/components/editor/editor-pane/autocompletion/code-block.ts, src/components/editor/editor-pane/autocompletion/collapsable-block.ts, src/components/editor/editor-pane/autocompletion/container.ts, src/components/editor/editor-pane/autocompletion/emoji.ts, src/components/editor/editor-pane/autocompletion/header.ts, src/components/editor/editor-pane/autocompletion/image.ts, src/components/editor/editor-pane/autocompletion/index.ts, src/components/editor/editor-pane/autocompletion/link-and-extra-tag.ts, src/components/editor/editor-pane/autocompletion/pdf.ts, src/components/editor/editor-pane/editor-pane.tsx
Editor
This PR changes the auto completion behaviour. Auto completion will only react for words that are separated by space (or space like characters)
Closes #593
=> replace allowedChars with not-whitespace

src/components/common/download/download.ts, src/components/editor/document-bar/revisions/utils.ts, src/components/history-page/history-page.tsx, src/components/history-page/utils.ts
Common methods
Until now we had three places where we did a download of content: Revisions, History and Editor content. They all use the same technique to download files.
To reduce code duplication, this PR adds a common helper function `download(data, fileName, mimeType)` that does the thing.
none
=> Add common download helper

src/components/editor/app-bar/help-button/help-button.tsx
help modal
This PR fixed the size of the help modal.
after we added tabs in the help modal, the modal doesn't need to be xl anymore as it has way to much empty space that way.
=> fixed help modal width

src/components/editor/editor-pane/autocompletion/code-block.ts, src/components/editor/editorTestContent.ts, src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
editor
This PR adds js as an extra highlight language. Also the auto completion show all diagrams and extra languages we support. 
fixes #258
=> added js as an extra highlighted language

package.json
package.json scripts,  in turn CI linting job
This PR sets the maximum number of allowed warnings during linting to 0, thereby enforcing completely fine linted code.
I tested the change locally with a prepared code snippet.
none
=> Enforce no warnings during linting

CHANGELOG.md, cypress/integration/profile.spec.ts, public/api/v2/tokens, public/locales/en.json, src/api/tokens/index.ts, src/api/tokens/types.d.ts, src/components/common/icon-button/icon-button.tsx, src/components/profile-page/access-tokens/profile-access-tokens.tsx, src/components/profile-page/profile-page.tsx
Profile page
This PR adds the access token management section to the profile. I chose the wording "Access token" over "API key" as it sounds not that technical.
closes #647
=> Add access token management to profile

src/components/markdown-renderer/markdown-it-plugins/twitter-emojis.ts, src/external-types/markdown-it-emoji/index.d.ts
Emoji replacer
This PR replaces the used markdown it emoji plugin with the bare version, so it won't include an emoji definition.
=> Use bare version of markdown-it-emoji

src/components/markdown-renderer/full-markdown-renderer.tsx, src/components/markdown-renderer/hooks/use-replacer-instance-list-creator.ts, src/components/markdown-renderer/replace-components/task-list/task-list-replacer.tsx
Markdown renderer > Task Lists
This PR improves the task lists replacer. If no onTaskCheckedChange callback was provided, then the checkboxes will be disabled.
=> Disable check box if no onTaskCheckedChange is provided

public/locales/en.json
Translation files
moment.js had a flag that stripped these suffixes from their output, so that we could customize the messages more. luxon does not have this flag and therefore generates double suffixes.
This PR updates the translations to remove the additional suffix.
none
=> Removed 'ago'-suffix from translations

src/components/editor/app-bar/help-button/cheatsheet.tsx, src/components/markdown-renderer/markdown-it-configurator/BasicMarkdownItConfigurator.tsx, src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx
This PR moves alert container from full renderer to basic renderer.
=> moved alertContainer to basic renderer from full renderer

src/components/markdown-renderer/markdown-renderer.scss
In the html renderer output the link icon should be visible, when hovering over a header.
This PR fixes the visibility of the link icon, when hovering over a header.
=> fix anchor links

.github/workflows/e2e.yml
CI
When the pipeline is cancelled by a preceding failing job, the screenshot upload job won't run. This change adds the flag that it will run even when preceding jobs failed.
none
=> Always upload screenshots of errors

renovate.json
this adds Signed-off to the commit messages of renovate (see https://docs.renovatebot.com/presets-default/#gitsignoff)
=> added gitSignOff preset to renovate

cypress/support/config.ts
cypress tests
This PR fixes the path of the branding icon during cypress test runs.
none
=> Fixed branding icon path in mocked cypress config

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml
CI
This PR improves the caching of node_modules in the CI by binding the cache to the yarn.lock
Closes #760
=> Use safer node_modules cache

src/components/application-loader/application-loader.tsx, src/hooks/common/use-frontend-base-url.ts
Application Loader / Common hooks
This PR extracts the code for finding the frontend base url into a hook.
=> Extract windows location code into hook

.gitignore
Gitignore
This PR adds the new `.eslintcache` file to `.gitignore`
=> Ignore .eslintcache

CHANGELOG.md, src/components/editor/editor-pane/key-map.ts
editor
This PR removes the f9 shortcut to sort all lines in a pad
fixes #813
=> removed the f9 shortcut to sort all lines in a pad

renovate.json
Renovate
`markmap-view` and `markmap-lib` should be updated at once. This PR adds a new package group for renovate.
#831 #830
=> Add new package group for markmap

tsconfig.json
tsconfig
The current tsconfig gets adjusted by craco every time you run it with outdated settings.
`  - compilerOptions.jsx must be react-jsx (to support the new JSX transform in React 17)`
=> Change tsconfig for jsx transpiler

.gitignore, .idea/copyright/hedgedoc.xml, .idea/copyright/profiles_settings.xml, .idea/jsLinters/eslint.xml, .reuse/dep5
Jetbrains IDE settings
The core developers use webstorm, which has a handy method to add a copyright header to new files. This PR activates this feature.
=> Add jetbrains copyright autocomplection

src/hooks/common/use-frontend-base-url.ts
Helpers -> base Url hook
This PR fixes the base url hook  that always returned an empty string because from the pathname the pathname was eliminated. It should be that from the full URL the pathname gets removed.
=> Fix bug that pathname is always empty

CHANGELOG.md, public/locales/en.json, src/components/common/copyable/copyable-field/copyable-field.tsx, src/components/editor/app-bar/editor-view-mode.tsx, src/components/editor/document-bar/buttons/share-link-button.tsx, src/components/editor/editor.tsx, src/components/pad-view-only/pad-view-only.tsx, src/redux/document-content/methods.ts, src/redux/document-content/reducers.ts, src/redux/document-content/types.ts
Editor → document bar → share button
This PR improves the dialog that opens after clicking the share link button. It now includes two share-able URLs: One for the editor in the current view-mode and one for the read-only-view or presentation-view depending on the note type.
Fixes #790 
Fixes #791
=> Enhance share dialog

cypress/integration/editorMode.spec.ts, src/components/editor/app-bar/editor-view-mode.tsx, src/components/editor/editor.tsx
Editor
This PR adds support for respecting the editor-mode URL parameters (?both, ?edit, ?view).
When testing this branch, please note that the editor-mode enum has changed and therefore the localStorage-stored-settings won't work anymore unless you once click on one of the edit-view-both buttons once.
#860
=> Add support for editor-mode URL parameters

src/components/editor/editorTestContent.ts
Editor demo content
The youtube video we used in the demo content is down. This PR replaces the old youtube link with big buck bunny.
=> Replace youtube link with a working one

package.json
NPM task "start:dev"
IMHO it's very confusing, that there is a task "start" and a task "start:dev", which is for usage with a backend. Therefore I propose to rename the backend task
=> Rename npm task

.github/workflows/build.yml, .github/workflows/e2e.yml, README.md, package.json, src/index.tsx, src/utils/is-test-mode.ts
Environment
This PR adds a new environment variable "REACT_APP_TEST_MODE" which is set when the test build for cypress is built. Its a preparation for https://github.com/hedgedoc/react-client/pull/837 and https://github.com/hedgedoc/react-client/pull/896
=> Add test mode

src/components/markdown-renderer/hooks/use-replacer-instance-list-creator.ts, src/components/markdown-renderer/markdown-it-plugins/headline-anchors.ts, src/components/markdown-renderer/replace-components/external-links-in-new-tabs/external-links-in-new-tabs.tsx
Renderer
This PR adds a new replacer that changes links. External links will always open in a new tab.
=> Open links always in new tabs

CHANGELOG.md, cypress/integration/metadata.spec.ts, public/locales/en.json, src/components/editor/yaml-metadata/yaml-metadata.test.ts, src/components/editor/yaml-metadata/yaml-metadata.ts, src/components/markdown-renderer/full-markdown-renderer.tsx, src/components/markdown-renderer/replace-components/sequence-diagram/deprecation-warning.tsx, src/redux/document-content/reducers.ts
Editor
This PR adds support for yaml-arrays as definition of tags.
#872
=> Add ability to use yaml-array for tags

src/components/editor/document-renderer-pane/document-render-pane.tsx, src/components/editor/document-renderer-pane/scrolling-document-render-pane.tsx, src/components/editor/document-renderer-pane/use-adapted-line-markers-callback.ts, src/components/markdown-renderer/full-markdown-renderer.tsx
FullMarkdownRenderer
This PR moves the yaml-array deprecation warning from the `FullMarkdownRenderer` to the `DocumentRenderPane`. This is done, because the FullMarkdownRenderer should be independent from the Redux state, that is used to save the tags.
=> Move yaml-array warning to documentrenderpane

CHANGELOG.md, public/locales/en.json, src/components/editor/app-bar/help-button/shortcuts.tsx, src/components/editor/editor-pane/key-map.ts
editor
This PR adds a shortcut for the addLink functionality.
fixes #858
=> added shortcut for addLink (ctrl+k)

src/components/markdown-renderer/basic-markdown-renderer.tsx, src/components/markdown-renderer/full-markdown-renderer.tsx, src/components/markdown-renderer/hooks/use-extract-first-headline.ts, src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx, src/redux/document-content/methods.ts
redux states and title extraction logic
This PR fixes the fact that yaml-metadata as well as the first heading for the title are cached for too long even if the document has no content anymore.
=> Fix yaml metadata and document title not resetting on deletion

package.json, src/components/markdown-renderer/markdown-it-plugins/headline-anchors.ts, yarn.lock
Node dependencies
This PR replaces my fork of markdown-it-anchor with the original version, because it was updated.
=> Use original markdown-it-anchor

src/components/markdown-renderer/replace-components/image/lightbox.scss, src/components/markdown-renderer/replace-components/image/lightboxedImageFrame.tsx
Image Lightbox
This PR limits the lightbox size to the screen size.
=> Limit lightbox size

.idea/copyright/hedgedoc.xml
copyright template idea
This PR fixes the template to always use the current year.
signed-off my commits to accept the DCO.
=> fixed copyright template for idea

src/components/editor/editor-pane/tool-bar/table-picker/table-picker.tsx
"Insert table" overlay
This PR prevents, that the overlay and the modal are shown at the same time.
=> Don't show "create table" overlay if modal is showing

.github/workflows/e2e.yml, README.md, browserstack.json
GitHub actions workflows -> E2E browserstack
This PR adds branch information to the browserstack runs to easier identify them in the browserstack dashboard.
As @mrdrogdrog noted, the BrowserStack setup-env GitHub action has a field for build-name and project-name, but several commits (273772d, 928d312, 2f287b9, 4d53819, 216a90d, 7432e16, 09a39d8, 9ac28c4) showed they aren't working as expected.
Regarding the git commit sha extraction:
GitHub runs the tests in PRs against a simulated merge-commit with the base-branch. The commit SHA that is outputted by either git itself or by `${{github.sha}}` therefore is useless. Luckily GitHub provides the SHA of the commit that triggered a PR-run in a separate variable `${{github.event.pull_request.head.sha}}`. This variable isn't set on pushes to …
=> Add branch info to browserstack runs

cypress/integration/documentTitle.spec.ts, src/components/markdown-renderer/hooks/use-extract-first-headline.ts
title extraction
This PR improves the title extraction to leave out latex code, but include latex output.
e.g
```
```
puts `α-foo` as the title
concerns #815
=> fixed title extraction to exclude latex code, but include rendered latex

src/components/markdown-renderer/replace-components/external-links-in-new-tabs/external-links-in-new-tabs.tsx
Markdown renderer replacer for external links
This PR limits the attributes that are provided to external links in the external link replacer.
=> Limit attributes for external links

package.json, src/components/markdown-renderer/replace-components/abc/abc-frame.tsx, src/components/markdown-renderer/replace-components/abc/abc.scss, src/style/index.scss, src/style/variables.scss, yarn.lock
ABC-JS Dependency
This PR updates abc.js to version 6 beta.
=> Update abc js to version 6-beta

package.json
This PR fixes under which domain the serve:build script runs the frontend.
This makes the iframe work in this mode
=> change domain in build:serve script

src/components/markdown-renderer/replace-components/abc/abc-frame.tsx
This PR sets the text-color of ABCFrame to always be black 
fixes #977
=> ABCFrame text-color is always black

renovate.json
Renovate
This PR adds `markmap-common` to the `markmap` group
#993 #994
=> Include markmap-common in renovate group

src/components/markdown-renderer/replace-components/abc/abc-frame.tsx, src/external-types/abcjs/abcjs.d.ts
ABC.js rendering
This PR removes our custom types for ABC.js, because they are included into the upstream package.
=> Remove custom abcjs types

src/components/application-loader/initializers/i18n.ts
i18n configuration
i18n spams its debug messages into the console. This PR disables this behaviour in production mode.
=> Don't show i18n messages in production mode

cypress/integration/diagrams.spec.ts, cypress/integration/linkEmbedder.spec.ts, cypress/integration/shortcodes.spec.ts, cypress/support/config.ts, src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx, src/components/markdown-renderer/replace-components/gist/gist-frame.tsx, src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx, src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx, src/components/markdown-renderer/replace-components/youtube/youtube-frame.tsx
E2E tests
This PR adds e2e tests for diagrams and embeddings. As most of the diagrams only yield a `svg` element into the DOM, the tests can ensure that some svg element is visible, but can't ensure that it really belongs to the tested diagram.
Closes #1022
=> Add e2e tests for diagrams and embeddings

package.json, src/components/editor-page/sidebar/export-markdown-sidebar-entry.tsx, yarn.lock
Editor -> export -> markdown file
This PR sets the note title as filename for markdown download. It will be sanitized to ensure to not break any filesystems.
none
=> Set sanitized note title as filename for download

CHANGELOG.md, cypress/integration/autocompletion.spec.ts, cypress/integration/banner.spec.ts, cypress/integration/diagrams.spec.ts, cypress/integration/documentTitle.spec.ts, cypress/integration/editorMode.spec.ts, cypress/integration/export.spec.ts, cypress/integration/fileUpload.spec.ts, cypress/integration/helpDialog.spec.ts, cypress/integration/highlightedCodeBlock.spec.ts, cypress/integration/history.spec.ts, cypress/integration/import.spec.ts, cypress/integration/intro.spec.ts, cypress/integration/language.spec.ts, cypress/integration/link.spec.ts, cypress/integration/linkEmbedder.spec.ts, cypress/integration/maxLength.spec.ts, cypress/integration/profile.spec.ts, cypress/integration/quote-extra.spec.ts, cypress/integration/shortcodes.spec.ts, cypress/integration/signInButton.spec.ts, cypress/integration/toolbar.spec.ts, cypress/integration/yamlArrayDeprecationMessage.spec.ts, cypress/support/config.ts, src/api/auth/index.ts, src/components/landing-layout/navigation/sign-in-button.tsx
Sign-in button in the app-bar
This PR improves the sign-in button as this links now directly to the auth-provider if only one provider is enabled which doesn't require additional user input in our frontend.
Note that the e2e tests currently fail due to a cypress limitation for which we need to find a workaround.
@mrdrogdrog: Sentences in the tests. Only for you.
Closes #1042
=> Add one-click login if possible

src/components/editor-page/editor-page.tsx, src/components/editor-page/render-context/iframe-communicator-context-provider.tsx, src/components/editor-page/renderer-pane/render-iframe.tsx
Edit page
This PR creates a react context for the iframe communicator. This is useful if some functions (like sidebar actions) should be able to communicate with the renderer.
=> Add context for iframe communicator in editor page

renovate.json
Vega lite
This PR adds a renovate group for all vega lite packages
=> Add renovate group for vega lite

package.json, yarn.lock
yarn.lock / packages
This reverts commit 65bdf545794f23350686b5ef3cc1babfb92542c4. This is needed because the d3 update breaks markmap.
Reverts #1154
=> Revert "Update dependency d3-graphviz to v4"

renovate.json
Renovate
This PR improves the renovate config by:
- Reorganizing the file structure
- Adding new groups
- Renaming some groups
- Replacing package match rules
=> Improve renovate config by adding new groups

public/api/v2/config
Frontend mock config
This PR changes the plantuml server url in the mock config file to "https".
=> Change plantuml server url to https

cypress/integration/linkSchemes.ts, src/components/markdown-renderer/replace-components/link-replacer/link-replacer.tsx
This PR blocks URIs that begin with `data:` or `javscript:` to avoid something like XSS attacks.
Fixes #1185
=> Disallow data and javascript URIs

src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.scss
Code Highlighting
This PR fixes the wrong indentation in non-wrapped code highlighted blocks in the markdown render output.
=> Fix code highlight indentation

package.json, src/components/markdown-renderer/replace-components/markmap/markmap-loader.ts, src/external-types/markmap-lib/index.d.ts, yarn.lock
Markmap
This PR changes the markmap import to a explicit file. 
If we use the default import then webpack will use the "browser" bundle which relies on CDN lazy loading of dependencies.
=> Use module build of markmap-lib

src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.scss, src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.tsx
This PR changes some aspects of the table picker:
- Fix error that the border of table cells was invisible in dark mode
- Add margin to table cells
- Add full border to table cells
- Change border-color while hovering over table cells
=> TablePicker: Change table cells in picker

CHANGELOG.md, package.json, src/components/history-page/history-page.tsx, src/components/history-page/history-toolbar/history-toolbar.tsx, yarn.lock
History page
This PR adds URL parameters for the search field and the tags filter on the history page. This allows users to create bookmarks in their browser for often used searches/filters.
When no filters are set, the URL remains at `/history`.
When the search field is e.g. set to "test", the URL will be `/history?search=test`.
When the following tags are set: "hedgedoc" and "test", the URL will be `/history?tags=hedgedoc&tags=test`.
Search and tags parameter can be combined.
This PR is part of "The History PR" series.
Part I: Move to redux (#1156)
Part II: Add URL params (this)
Part III: Editor integration (#1158)
Part IV: Generalize components for explore page (coming soon)
See also #407
=> The History PR: II - Add URL params

cypress/integration/intro.spec.ts, src/components/intro-page/hooks/use-intro-page-content.ts, src/components/intro-page/intro-page.tsx
Intro page
This PR changes the behaviour of the intro page. If no intro could be fetched then the output should be blank.
=> Don't show error if no intro.md was found

src/components/intro-page/intro-page.tsx
Intro-Page
The spinner on the intro page doesn't hide after the page load. This PR fixes this bug.
=> Fix spinner visibility on intro-page

cypress/integration/taskLists.spec.ts, src/redux/note-details/reducers.ts
Redux method for updating the checkbox state of a line
This PR fixes the regex that is used to identify the `[ ]` checkbox part when updating the markdown content for a clicked todo-list item. The previous regex could only detect todo-list items that start with a `-` or `*`. But `+` is a valid unordered list bullet point as well and numbered lists should also be supported.
This PR changes the regex to reflect this and adds tests for the todo-list feature.
Fixes hedgedoc/hedgedoc#1220
=> Fix task list checkboxes for numbered lists

CHANGELOG.md, src/components/editor-page/editor-page.tsx, src/components/editor-page/hooks/useUpdateHistoryEntry.ts, src/components/editor-page/hooks/useUpdateLocalHistoryEntry.ts, src/components/editor-page/sidebar/pin-note-sidebar-entry.tsx, src/components/editor-page/sidebar/style/colors.scss
Editor + sidebar (pin to history)
This PR adds the integration of the history features into the editor page. This means the following:
- When a valid note is opened, a history entry is created or the last visited date is updated.
- When the title or tags of a note change, the history entry will be updated.
- The pinning state of the note is reflected in the sidebar. A click will toggle that state.
This PR is part of "The History PR" series.
Part I: Move to redux (#1156)
Part II: Add URL params (#1157)
Part III: Editor integration (this)
Part IV: Generalize components for explore page (coming soon)
Closes #331
=> The History PR: III - Editor integration

check-build-env-vars.js, package.json
Build environment
This PR replaces the bash script in the `build:production` task with a js file. This eliminates bash as build dependency.
=> Replace bash dependency with nodejs script

src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
markdown renderer -> code highlighting
highlight.js 11.0.0 deprecated the `highlight()` call parameters we used. This PR changes the call to the new signature to avoid future breakings.
See also: https://github.com/highlightjs/highlight.js/blob/main/CHANGES.md#version-1100
#1292
=> Replace deprecated highlight.js syntax

src/components/editor-page/editor-page.tsx, src/components/editor-page/splitter/splitter.scss, src/components/editor-page/splitter/splitter.tsx, src/components/markdown-renderer/markdown-renderer.scss, src/components/markdown-renderer/replace-components/abc/abc-frame.tsx, src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx, src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx, src/redux/note-details/methods.ts
Split component
This PR fixes the split component. If you stop holding down your mouse button while the mouse is not on the document after starting the resizing mode, then the splitter isn't stuck in resizing mode anymore.
You can also move your mouse over the whole document to resize the split.
=> Fix splitter

cypress/integration/fileUpload.spec.ts, public/mock-backend/api/private/media/upload-post, src/api/media/index.ts, src/components/common/upload-image-mimetypes.ts, src/components/editor-page/editor-pane/tool-bar/upload-image-button.tsx, src/components/editor-page/editor-pane/upload-handler.ts
Upload
This PR removes the pdf mime type and adds a upload mock response.
=> Remove pdf mimetype + Add upload mock response (3/3)

cypress/integration/autocompletion.spec.ts, cypress/integration/emoji.spec.ts
Signed-off-by: Tilman Vatteroth <git@tilmanvatteroth.de>
E2E tests
This PR adds an extra test suite for the emoji substitution.
=> Add extra test suite for emojis

src/components/editor-page/render-context/iframe-editor-to-renderer-communicator-context-provider.tsx, src/components/editor-page/render-context/iframe-renderer-to-editor-communicator-context-provider.tsx, src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts, src/components/editor-page/renderer-pane/render-iframe.tsx, src/components/render-page/hooks/use-image-click-handler.ts, src/components/render-page/iframe-markdown-renderer.tsx
Iframe communicator
This PR improves the iframe communicator hooks by removing the undefined return type. The hooks should always receive an communicator from a provider because the components with the hook can't be used correctly without a communicator. If no communicator was provided then the application crashes with an error. The only way this should happen is because of misuse of the context.
=> Throw error if no communicator was found in a react context

src/components/editor-page/document-bar/document-info/document-info-line-word-count.tsx, src/components/editor-page/render-context/iframe-renderer-to-editor-communicator-context-provider.tsx, src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts, src/components/editor-page/renderer-pane/render-iframe.tsx, src/components/intro-page/intro-page.tsx, src/components/render-page/iframe-communicator.ts, src/components/render-page/iframe-editor-to-renderer-communicator.ts, src/components/render-page/iframe-markdown-renderer.tsx, src/components/render-page/iframe-renderer-to-editor-communicator.ts, src/redux/editor/methods.ts, src/redux/editor/reducers.ts, src/redux/editor/types.ts
Iframe communication
This PR adds a new state to the redux store. This state defines if the iframe renderer is ready and e.g. is used for the word count display.
=> Add renderer ready state to global application state

cypress/support/getMarkdownRenderer.ts, src/components/editor-page/renderer-pane/render-iframe.tsx
Iframe rendering
Some tests fail because the iframe hasn't loaded the inner hedgedoc renderer yet
but cypress tries to travel through the dom and verify the render results.
This PR fixes the race condition by forcing cypress to wait until the renderer is ready.
=> Add new data property to iframe that indicates if the content is ready.

src/components/editor-page/document-bar/document-info/document-info-line-word-count.tsx, src/components/editor-page/renderer-pane/render-iframe.tsx, src/components/intro-page/intro-page.tsx, src/redux/editor/methods.ts, src/redux/editor/reducers.ts, src/redux/editor/types.ts, src/redux/index.ts, src/redux/renderer-status/methods.ts, src/redux/renderer-status/reducers.ts, src/redux/renderer-status/types.ts
Redux store
This PR extracts the renderer ready state into an extra redux state to prevent that the information gets serialized into the local storage.
Fixes #1342
=> Extract render ready status

src/components/document-read-only-page/document-read-only-page.tsx
Document read only mode
This PR fixes the error on the document read only page by adding the missing context provider
=> Fix context error in view only

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml
CI e2e tests
This PR changes the cache key for the build directory in e2e tests to use the commit hash. By doing this the CI don't have to rebuild the same commit if the job gets restarted. 
(It also renames some misnamed steps.)
=> Reuse cache for e2e

CONTRIBUTING.md
Contributing docs
This PR adds codestyle documentation for our contributing docs.
=> Add codestyle docs

src/components/editor-page/editor-pane/autocompletion/link-and-extra-tag.ts, src/redux/api-url/methods.ts, src/redux/api-url/reducers.ts, src/redux/api-url/types.ts, src/redux/banner/methods.ts, src/redux/banner/reducers.ts, src/redux/banner/types.ts, src/redux/config/methods.ts, src/redux/config/reducers.ts, src/redux/config/types.ts, src/redux/dark-mode/methods.ts, src/redux/dark-mode/reducers.ts, src/redux/dark-mode/types.ts, src/redux/editor/methods.ts, src/redux/editor/reducers.ts, src/redux/editor/types.ts, src/redux/history/methods.ts, src/redux/history/reducers.ts, src/redux/history/types.ts, src/redux/index.ts, src/redux/note-details/reducers.ts, src/redux/note-details/types.ts, src/redux/ui-notifications/reducers.ts, src/redux/ui-notifications/types.ts, src/redux/user/methods.ts, src/redux/user/reducers.ts, src/redux/user/types.ts
Redux types
This PR reorganizes the redux types so you don't have to cast the actions in the reducers.
=> Reorganize redux types to avoid unnecessary type casting

src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.scss
Code Highlighting
This PR fixes the layout of the code lighting component.
=>
=> Fix code highlighting grid

package.json, yarn.lock
ESLint
This PR removes the package "eslint-plugin-flowtype" because we don't use [flowtype](https://flow.org/).
=> Remove package "eslint-plugin-flowtype"

renovate.json
Renovate
This PR changes the renovate config:
- change version range strategy from "always pin" to "autodetect pin" by removing the config extension as the auto detection is already covered by `config:base`. (see https://docs.renovatebot.com/configuration-options/#rangestrategy).
- Remove `dependencyDashboard` as it is already covered by `config:base`
=> Optimize renovate config

public/locales/en.json, src/components/editor-page/editor-pane/autocompletion/code-block.ts, src/components/editor-page/sidebar/pin-note-sidebar-entry.tsx, src/components/editor-page/use-notification-test.tsx, src/components/history-page/history-content/history-content.tsx, src/components/history-page/history-page.tsx, src/components/history-page/history-toolbar/clear-history-button.tsx, src/components/history-page/history-toolbar/history-toolbar.tsx, src/components/history-page/history-toolbar/import-history-button.tsx, src/components/notifications/ui-notification-toast.tsx, src/redux/ui-notifications/methods.ts, src/redux/ui-notifications/reducers.ts, src/redux/ui-notifications/types.ts
Notifications
This PR improves the UI notifications
- dispatchUINotification returns a promise that contains the notification id
- notifications use i18n instead of plain text
=> Rework notifications

src/components/markdown-renderer/replace-components/csv/csv-parser.ts
CSV parser
This PR fixes a DoS attack in the CSV parser by escaping the delimiter to prevent that the delimiter can be interpreted as regex character.
=> Fix DoS in CSV parser

src/components/markdown-renderer/replace-components/abc/abc.scss
ABC.js frame
When the render view is to small then the abc js score is cut off. This PR adds an overflow scrollbar.
=> Fix missing scrollbars for abcjs overflow

CHANGELOG.md, src/components/markdown-renderer/replace-components/gist/gist-frame.scss, src/components/markdown-renderer/replace-components/gist/gist-frame.tsx, src/components/markdown-renderer/replace-components/gist/use-resize-gist-frame.ts
Gist replacer
This PR replaces our custom gist frame implementation with the github embedding url (like https://gist.github.com/ErikMichelson/1fcd4867c3740dc1c9e3e78eb6dc2070.pibb).
=> Replace custom gist implementation with github rendering

src/components/document-read-only-page/document-read-only-page.tsx, src/components/editor-page/editor-document-renderer/editor-document-renderer.tsx, src/components/editor-page/editor-page.tsx, src/components/editor-page/editor-pane/editor-pane.tsx, src/components/editor-page/sidebar/export-markdown-sidebar-entry.tsx, src/hooks/common/use-note-markdown-content-without-frontmatter.ts, src/hooks/common/use-note-markdown-content.ts, src/redux/note-details/initial-state.ts, src/redux/note-details/reducer.ts, src/redux/note-details/types.ts
This PR:
- Renames "documentContent" to "markdownContent" in the redux state and removes the old "markdownContent". This is done because the only place where we need the markdown content without frontmatter is in the rendering. A new hook does this task now.
- Fixes the update of the note title if frontmatter gets removed.
=> Remove document content

src/components/editor-page/editor-pane/editor-pane.tsx
Editor pane
This PR removes an unneeded props interface that was used in editor-pane
=> Remove unneeded props interface

src/components/markdown-renderer/basic-markdown-renderer.tsx, src/components/markdown-renderer/markdown-it-configurator/basic-markdown-it-configurator.ts
Markdown it configurator
This PR removes some deprecated and dead code. It's not necessary anymore because markdown it doesn't parses the frontmatter anymore.
=> Remove deprecated code in basic markdown-it configurator

cypress/integration/autocompletion.spec.ts, cypress/integration/highlightedCodeBlock.spec.ts, src/components/editor-page/app-bar/help-button/help-modal.tsx, src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.scss, src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
Code highlighting and help modal
This PR fixes some minor bugs I encountered while testing something else.
- The code highlighting in the cheatsheet renders correctly now
- The code highlighting uses a dark theme that actually overwrites the colors of the light theme
- The size of the help modal got increased.
=> Fix code highlighting

src/components/markdown-renderer/slideshow.scss
RevealJs
This PR changes the scss import of reveal.js to the css file to get rid of the sass deprecation warning.
=> Change scss import of reveal to css

CHANGELOG.md
Signed-off-by: Stéphane Guillou <stephane.guillou@member.fsf.org>
Note that the FAQ doesn't give a MathJax vs KaTeX explanation just yet.
Some reasons for the switch are here: https://github.com/hedgedoc/react-client/issues/495
Client changelog
Correct a dead link.
None
=> fix dead link to FAQ

src/components/notifications/ui-notification-toast.tsx
Notification
This PR removes the `useMemo` from the interval in the ui-notification component because the value is not complex.
=> Remove useMemo from interval

src/components/common/modals/common-modal.tsx, src/components/common/modals/deletion-modal.tsx, src/components/common/motd-modal/motd-modal.tsx, src/components/editor-page/app-bar/help-button/cheatsheet-tab-content.tsx, src/components/editor-page/app-bar/help-button/help-modal.tsx, src/components/editor-page/app-bar/help-button/links-tab-content.tsx, src/components/editor-page/app-bar/help-button/shortcuts-tab-content.tsx, src/components/editor-page/document-bar/document-info/document-info-modal.tsx, src/components/editor-page/document-bar/permissions/permission-modal.tsx, src/components/editor-page/document-bar/revisions/revision-modal.tsx, src/components/editor-page/document-bar/share/share-modal.tsx, src/components/editor-page/editor-modals/max-length-warning-modal.tsx, src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preferences.tsx, src/components/editor-page/editor-pane/tool-bar/table-picker/custom-table-size-modal.tsx, src/components/editor-page/sidebar/delete-note-sidebar-entry.tsx, src/components/history-page/entry-menu/dropdown-item-with-deletion-modal.tsx, src/components/history-page/history-toolbar/clear-history-button.tsx, src/components/landing-layout/footer/version-info/version-info-modal.tsx, src/components/markdown-renderer/markdown-extension/image/image-lightbox-modal.tsx, src/components/profile-page/access-tokens/profile-access-tokens.tsx
Modals
This PR reworks the Props of the most modals by:
- Renaming some of the props to make their intend a bit more clear
- Remove some duplicated props that contain "show" and "onHide"
=> Deduplicate CommonModal Props

src/components/editor-page/editor-pane/editor-pane.tsx, src/components/editor-page/editor-pane/hooks/use-create-status-bar-info.ts, src/components/editor-page/editor-pane/max-length-warning/max-length-warning-modal.tsx, src/components/editor-page/editor-pane/max-length-warning/max-length-warning.tsx, src/components/editor-page/editor-pane/status-bar/cursor-position-info.tsx, src/components/editor-page/editor-pane/status-bar/number-of-lines-in-document-info.tsx, src/components/editor-page/editor-pane/status-bar/remaining-characters-info.tsx, src/components/editor-page/editor-pane/status-bar/selection-info.tsx, src/components/editor-page/editor-pane/status-bar/separator-dash.tsx, src/components/editor-page/editor-pane/status-bar/status-bar.tsx
Editor
This PR restructures the max length warning modal and the status bar.
=> Restructure the max-length-warning and the status bar

CHANGELOG.md, cypress/integration/iframe-capsule.ts, src/components/markdown-renderer/hooks/use-markdown-extensions.ts, src/components/markdown-renderer/markdown-extension/iframe-capsule/iframe-capsule-markdown-extension.ts, src/components/markdown-renderer/markdown-extension/iframe-capsule/iframe-capsule-replacer.tsx, src/components/markdown-renderer/replace-components/click-shield/click-shield.scss, src/components/markdown-renderer/replace-components/click-shield/click-shield.tsx
This PR adds a new markdown extension that capsulses iframes in click shields
Closes #1581
=> Iframe capsule

src/components/editor-page/editor-pane/status-bar/selection-info.tsx
editor bottom bar
Seems like I forgot to remove a console.log that was for debugging purposes. This PR removes it.
=> Remove console.log

src/components/history-page/history-toolbar/history-view-mode-toggle-button.tsx
HistoryViewModeToggleButton 
This PR fixes the text direction
fixes #1725
=> fix: use text direction auto

global-styles/index.scss, global-styles/markdown-tweaks.scss, global-styles/variables.module.scss, global-styles/variables.scss, src/components/editor-page/editor-pane/extended-codemirror/codemirror.module.scss, src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx, src/components/markdown-renderer/markdown-extension/abcjs/abc.module.scss, src/components/markdown-renderer/markdown-extension/flowchart/flowchart.tsx
Emoji rendering
This PR
- deduplicates the definitions of font family rules
- Adds a work around for the macos emoji problem by prefering the system emojis on macos
Fixes #1615
=> Import emojis from scss and work around emoji bug on macos

cypress/integration/motd.spec.ts, src/components/application-loader/initializers/fetch-motd.ts
Motd
Some hosters (like vercel.app) don't provide a "last modified" header, but an etag. 
This PR includes the etag into the motd "last modified" check.
=> Add etag header to last modified check of motd

.github/workflows/e2e.yml
CI
This PR excludes the next cache from the artifact upload. This reduces the artifact since from 200 to 20 MB.
=> Don't upload cache to build artifact

.github/workflows/e2e.yml
CI
The default install command of the cypress action uses "--frozen-lockfile" which is not available in yarn berry. This PR adds a custom install command for yarn berry.
=> Use yarn berry install command in cypress action

.github/workflows/e2e.yml
E2E tests
This PR reduces the number of containers for the e2e test to 5 so chrome and firefox can run at the same time.
=> Reduce number of e2e containers to 5

src/components/common/modals/common-modal.tsx
Modals
This PR adds a condition to the DOM generation of modals.
This way we prevent unwanted data loading, invisible updates
and visual artifacts when the modal isn't visible.
=> Add condition to modal

src/components/markdown-renderer/document-markdown-renderer.tsx, src/components/markdown-renderer/slideshow-markdown-renderer.tsx
Renderer
This PR removes an redundant Ref (and ref update callback) that caused the TOC to disappear.
=> Remove redundant toc ref

src/components/markdown-renderer/markdown-extension/plantuml/plantuml-markdown-extension.ts
PlantUML Extension
This PR adds the plantuml-not-configured tag to the dom purify whitelist.
=> Add plantuml not configured tag to tag name whiteliste

src/components/markdown-renderer/hooks/use-on-ref-change.ts, src/components/markdown-renderer/markdown-extension/graphviz/graphviz-frame.tsx
Graphviz frame
This PR fixes a bug that causes a log loop in the graphviz frame.
=> Remove unnecessary effect dependency

.github/workflows/deploy.yml, netlify.toml, netlify/build.sh, netlify/deploy.sh
PR deployments
This PR fixes/enhances three things of the deployments:
GitHub deployment links were overriden by different PRs because we used the same environment across every PR. This PR adds a new environment per PR in the workflow.
The main deployment broke due to the yarn build command not executed. This PR adds a build script which executes the command when not being in GitHub actions.
The app.netlify.com Interface had no information about the deployed branch and only labeled the deployments as "Branch deployment". This PR adds a message containing the PR number and title to each deployment.
none
=> deployments: Fix main branch deployment and overrides

.github/workflows/deploy.yml, netlify/deploy.sh
netlify deployments
This PR removes the branch name from the deployment alias since slashes (and other special characters) are known to break the deployment URLs, which then result in an error 404.
See https://github.com/netlify/cli/issues/969
none
=> Fix netlify not using aliases containing a slash

cypress/integration/fileUpload.spec.ts, cypress/integration/history.spec.ts, cypress/integration/import.spec.ts, cypress/support/index.ts, package.json, yarn.lock
Cypress
"cypress-file-upload" isn't necessary anymore. Cypress has this functions itself. Now also with mime types.
https://docs.cypress.io/api/commands/selectfile#Usage
=> Replace "cypress-file-upload" with cypress selectFile

renovate.json
Renovate
This PR fixes the renovate match string to detect docker image tags correctly.
Fixes #1855
=> Fix renovate match string for docker images

src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-modal.tsx, src/components/history-page/entry-menu/delete-note-item.tsx, src/components/history-page/entry-menu/dropdown-item-with-deletion-modal.tsx, src/components/history-page/history-card/history-card.tsx
Note deletion modal
This PR removed duplicate note deletion modal
fixes #1731
=> refactor: Deduplicate delete modal

src/components/markdown-renderer/hooks/use-markdown-extensions.ts
Markdown Rendering
This PR fixes a bug in the rendering pipeline.
During the markdown-to-react conversion (which happens in the rendering, NOT in an effect) the toc is posted via callback from the markdown it instance. 
This callback sets the toc in the state of a higher component. This triggers the re-rendering of the sidebar. 
This causes an error because a state update in another component is done during the rendering of the markdown document.
This PR moves the execution of the callback into an effect that is triggered AFTER the rendering.
=> Post toc after rendering and not during it

.github/workflows/deploy-main.yml
Main branch deployment
The main branch deployment is broken because the github deployment api can't handle the number of states of the main branch.
This PR removes the deployment api requests from the main deployment workflow so it doesn't crash anymore and executes the netfliy cli again.
The deployment API is useful to see where I can find the current deployment of a branch. It shouldn't hurt us a lot because the URL for the main branch is always the same: https://hedgedoc.dev
=> Removes the github deployment api from the main branch deployment

.github/workflows/e2e.yml
CI
Okay I'm just done. Firefox in our current CI is just the WORST. It is slower than chrome and crashes A LOT! Like really! The e2e workflows of some PRs have to run 4 or 5 times because firefox decides to just loose the connection. 
This may also be caused by the performance of GHA, but right now it's easier to (temporaly) remove firefox than switching to a whole new CI.
Just to be clear: I know that this step isn't optimal. I know that a huge part of our community uses firefox. But right now the flakiness of the firefox CI runs drives me crazy!
At the moment we need the e2e tests just for our development to make sure that we don't accidentally break something.
We can readd firefox again when it's stable to use. Or when we have shifted enough of the e2e tests to jest. It would be nice …
=> Remove Firefox from CI

README.md
project README
This removes the duplicated "lint" badge in the README. This probably originated from the time when lint and prettier checks were two workflows.
none
=> Remove duplicated badge in README

.github/workflows/e2e.yml
E2E Workflow
This PR updates the cypress browsers image because renovate can't do that.
=> Update Cypress browsers to node16.13.2-chrome100-ff98

package.json, src/redux/index.ts, yarn.lock
Redux store creationg
Since redux [4.2.0](https://github.com/hedgedoc/react-client/pull/2015) the preferred way to create a store is `configureStore` because `createStore` is deprecated. This PR changes the necessary code for store creation.
=> Create store using redux-toolkit

src/components/markdown-renderer/markdown-extension/highlighted-fence/highlighted-code.tsx, src/components/markdown-renderer/markdown-extension/highlighted-fence/hooks/use-async-highlight-js-import.tsx, src/components/markdown-renderer/markdown-extension/highlighted-fence/hooks/use-code-dom.tsx
Highlighted Code Component
This PR extracts the actual code highlighting using hljs from the async call to prevent the waiting spinner to show up.
=> Extract code highlighting from async call

next.config.js, src/components/application-loader/initializers/setupI18n.ts, src/components/application-loader/loading-screen/random-icon.tsx, src/components/editor-page/document-bar/note-info/note-info-line-created.tsx, src/components/editor-page/document-bar/note-info/note-info-line-updated.tsx, src/components/notifications/ui-notification-toast.tsx, src/components/notifications/ui-notifications.tsx, src/redux/note-details/initial-state.ts, src/redux/note-details/reducers/build-state-from-set-note-data-from-server.test.ts, src/redux/note-details/reducers/build-state-from-set-note-data-from-server.ts, src/redux/note-details/types/note-details.ts, src/redux/ui-notifications/methods.ts, src/redux/ui-notifications/types.ts
LoadingScreen, i18n and rendering in general
This PR fixes some problems:
- [Disable react strict mode to prevent double rendering](https://github.com/hedgedoc/react-client/pull/2039/commits/eaa753bf28af4d43832ef5eaf5ad24a90fa1b590)
- [Use correct method to set i18n into debug mode](https://github.com/hedgedoc/react-client/pull/2039/commits/b5a1b19f10a788d0f2325c0bcad1e6b721a33e0c)
- [Prevent react hydration error](https://github.com/hedgedoc/react-client/pull/2039/commits/ab3fd5882a47eadf3534d0199aa9f5c2c3a934c2)
- [Replace Luxon DateTime with number in redux state](https://github.com/hedgedoc/react-client/pull/2039/commits/cd7e3fd52a91d2a60588bceaf019cba5432d807f)
=> Fix multiple problems

src/components/editor-page/editor-pane/editor-pane.tsx, src/components/markdown-renderer/markdown-extension/abcjs/abc-frame.test.tsx, src/components/markdown-renderer/markdown-extension/code-block-markdown-extension/code-block-markdown-plugin.ts, src/components/markdown-renderer/markdown-extension/code-block-markdown-extension/code-block-parameters.test.ts, src/components/markdown-renderer/markdown-extension/code-block-markdown-extension/code-block-parameters.ts, src/components/markdown-renderer/markdown-extension/code-block-markdown-extension/find-language-by-code-block-name.test.ts, src/components/markdown-renderer/markdown-extension/code-block-markdown-extension/find-language-by-code-block-name.ts
Code blocks in editor
This PR fixes the language detection in code blocks in code mirror.
Fixes #2063
=> Improve code blocks in editor

locales/en.json, src/components/editor-page/sidebar/user-line/user-line.tsx, src/components/editor-page/sidebar/users-online-sidebar-menu/active-indicator.tsx, src/components/editor-page/sidebar/users-online-sidebar-menu/users-online-sidebar-menu.tsx, src/redux/application-state.d.ts, src/redux/realtime/methods.ts, src/redux/realtime/reducers.ts, src/redux/realtime/reducers/build-state-from-add-user.ts, src/redux/realtime/reducers/build-state-from-remove-user.ts, src/redux/realtime/types.ts, src/redux/reducers.ts
Sidebar menu for online users
This PR connects the list of online users to the redux store instead of a mock list.
=> Connect list of online users in sidebar to redux

renovate.json
Renovate
This PR adds a new group for all codemirror dependencies.
=> Add renovate group for codemirror

src/components/editor-page/app-bar/editor-view-mode.tsx
editor > app bar
This PR switch editor and render view buttons in the editor.
This was done in an effort to sync the side of the button with the side of the component in the editor.
fixes #1236
=> feat: switch editor and render view buttons

src/components/notifications/notifications.module.scss
notifications
This PR fixes the position of notification-area to fixed.
This prevents notification to stick to the top of the page not able to be seen by users scrolled down the page.
fixes #1956
=> fix(notification): set position of notification-area to fixed

cypress/e2e/documentTitle.spec.ts, src/components/markdown-renderer/hooks/use-extract-first-headline.ts
First heading title extraction
This PR adds an [Mutation Observer](https://developer.mozilla.org/de/docs/Web/API/MutationObserver) to the found first headline element to detect async changes that have been made outside of the react rendering to the DOM-Elements.
Fixes #1816
=> Add mutation observer to first heading title extraction logic

src/components/editor-page/editor-pane/hooks/yjs/use-websocket-url.ts
Websocket URL generation
This PR fixes a crash that happens when the websocket URL can't be generated because the provided URL to the backend is relative.
=> Use window location as base url for websocket url construction

locales/en.json, src/api/notes/index.ts, src/components/common/note-loading-boundary/__snapshots__/create-non-existing-note-hint.test.tsx.snap, src/components/common/note-loading-boundary/__snapshots__/note-loading-boundary.test.tsx.snap, src/components/common/note-loading-boundary/create-non-existing-note-hint.test.tsx, src/components/common/note-loading-boundary/create-non-existing-note-hint.tsx, src/components/common/note-loading-boundary/note-loading-boundary.test.tsx, src/components/common/note-loading-boundary/note-loading-boundary.tsx, src/components/common/redirect.tsx, src/components/error-pages/common-error-page.tsx, src/pages/[id].tsx
error message if note is not found
This PR adds a button on the error page to create a non-existent note
fixes #1586
=> Add button to create note if not found

.eslintrc.json, .github/workflows/lint.yml, package.json, yarn.lock
Code linting
This PR adds the eslint-prettier-plugin that integrates the prettier code format checks into eslint.
=> Add eslint-plugin-prettier

package.json, yarn.lock
Packages
The package "redux-devtools-extension" is deprecated. It also seems like it isn't necessary anymore since redux toolkit (https://redux-toolkit.js.org/usage/usage-guide#store-setup).
=> Remove redux devtools package

src/components/editor-page/app-bar/help-button/help-button.tsx, src/components/editor-page/editor-pane/max-length-warning/max-length-warning.tsx, src/components/editor-page/renderer-pane/communicator-image-lightbox.tsx, src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-sidebar-entry.tsx, src/components/editor-page/sidebar/specific-sidebar-entries/note-info-sidebar-entry.tsx, src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry.tsx, src/components/editor-page/sidebar/specific-sidebar-entries/revision-sidebar-entry.tsx, src/components/editor-page/sidebar/specific-sidebar-entries/share-sidebar-entry.tsx, src/components/history-page/entry-menu/dropdown-item-with-deletion-modal.tsx, src/components/history-page/history-toolbar/clear-history-button.tsx, src/components/landing-layout/footer/version-info/version-info-link.tsx, src/components/profile-page/access-tokens/access-token-deletion-modal.tsx, src/components/profile-page/access-tokens/access-token-list-entry.tsx, src/components/profile-page/account-management/profile-account-management.tsx, src/hooks/common/use-boolean-state.ts
Modals
This PR adds a new state hook that controls modal visiblity.
=> Add modal visibility state hook

src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap, src/components/editor-page/splitter/splitter.tsx
Splitter
The splitter referenced an old css class '.splitter > .right' that doesn't exist anymore.
The HTML dom therefore rendered the right side of the splitter with an class name of 'undefined'.
This PR removes the invalid reference.
See https://github.com/hedgedoc/react-client/blob/main/src/components/editor-page/splitter/splitter.module.scss
none
=> Remove non-existing css class reference in splitter

.github/workflows/e2e.yml
CI E2E Test Workflow
This PR updates the version of the used cypress browser image.
=> Update cypress browser image to node16.14.2-slim-chrome103-ff102

src/components/editor-page/table-of-contents/__snapshots__/table-of-contents.test.tsx.snap, src/components/editor-page/table-of-contents/table-of-contents.test.tsx, src/components/editor-page/table-of-contents/table-of-contents.tsx, src/components/editor-page/table-of-contents/use-build-react-dom-from-toc-ast.tsx
Table of contents
This PR adds a memorized hook for the AST to React Element conversion.
Fixes #2180
=> Add memorized hook for table of contents

src/components/common/copyable/copy-to-clipboard-button/copy-to-clipboard-button.test.tsx, src/components/common/note-loading-boundary/__snapshots__/create-non-existing-note-hint.test.tsx.snap, src/components/common/note-loading-boundary/create-non-existing-note-hint.test.tsx, src/components/common/note-loading-boundary/create-non-existing-note-hint.tsx, src/components/common/user-avatar/user-avatar.test.tsx, src/utils/wait-for-other-promises-to-finish.ts
Component tests
This PR fixes some warnings in
- `copy-to-clipboard-button.test.tsx`
- `create-non-existing-note.test.tsx`
- `user-avatar.test.tsx`
=> Fixes warnings in some tests

.github/workflows/docker.yml
CI
The default value of "push" for the "build and push" action is false :upside_down_face: . 
This PR changes the value to true.
=> Enable push of docker images

src/components/editor-page/editor-pane/linter/frontmatter-linter.spec.ts, src/components/editor-page/editor-pane/linter/frontmatter-linter.ts
Frontmatter linter
This PR fixes the size of the highlighted part if the frontmatter is invalid.
=> Fix size of highlighting if frontmatter is invalid

locales/en.json, src/components/common/note-loading-boundary/__snapshots__/create-non-existing-note-hint.test.tsx.snap, src/components/common/note-loading-boundary/create-non-existing-note-hint.test.tsx, src/components/common/note-loading-boundary/create-non-existing-note-hint.tsx, src/components/common/note-loading-boundary/hooks/use-load-note-from-server.ts, src/components/common/note-loading-boundary/note-loading-boundary.tsx
Note Loading Boundary
If the note loading boundary creates a note then it tries to redirect the browser to the new URL to force a reload and load the editor. But since the current URL and the redirection URL are the same nothing happens. This PR modifies the boundary to do a refetch from the API instead.
=> Note Loading Boundary: Replace redirect with refetch from API

package.json, src/components/markdown-renderer/markdown-extension/__snapshots__/linkify-fix-markdown-extension.test.tsx.snap, src/components/markdown-renderer/markdown-extension/linkify-fix-markdown-extension.test.tsx, src/components/markdown-renderer/markdown-extension/linkify-fix-markdown-extension.ts, yarn.lock
renderer
This PR fixes the autodetection of linkify.
closes #2304
=> feat: configure linkify in markdownit with tlds

src/components/markdown-renderer/markdown-extension/gist/replace-legacy-gist-short-code.ts, src/components/markdown-renderer/markdown-extension/legacy-short-codes/replace-legacy-pdf-short-code.ts, src/components/markdown-renderer/markdown-extension/legacy-short-codes/replace-legacy-slideshare-short-code.ts, src/components/markdown-renderer/markdown-extension/legacy-short-codes/replace-legacy-speakerdeck-short-code.ts, src/components/markdown-renderer/markdown-extension/vimeo/replace-legacy-vimeo-short-code.ts, src/components/markdown-renderer/markdown-extension/vimeo/replace-vimeo-link.ts, src/components/markdown-renderer/markdown-extension/youtube/replace-legacy-youtube-short-code.test.ts, src/components/markdown-renderer/markdown-extension/youtube/replace-legacy-youtube-short-code.ts, src/components/markdown-renderer/markdown-extension/youtube/replace-youtube-link.test.ts, src/components/markdown-renderer/markdown-extension/youtube/replace-youtube-link.ts
Youtube embedding
This PR improves the yt id regex by making it more strict.
=> fix: Use more strict youtube id regex

package.json, src/components/editor-page/editor-pane/hooks/yjs/websocket-connection.ts, yarn.lock
realtime communication
When a user left a realtime-note, the awareness tried to send events even after the socket was closed, resulting in the app crashing.
This fix adds the check that the socket is still open before sending any messages.
none
=> fix(websocket): error when leaving realtime-note

.github/workflows/docker.yml, Dockerfile, src/version.json
Docker images
The current alpha deployment does not contain any information about the deployed version.
This PR adds a build argument to the Dockerfile to override the version string. For image built by the GitHub actions CI, it will be set to the commit that is used for the build.
none
=> Add build version to docker images

src/components/editor-page/editor-pane/hooks/yjs/websocket-connection.ts
Websocket connection
This PR fixes a error source by unbinding awareness events before destroying the awareness object.
=> Fix error when losing connection

.github/workflows/deploy-main.yml, .github/workflows/deploy-pr.yml
Github workflow
This PR fixes a wrong command in the main deployment workflow
=> Fix production build command in main deployment

.github/workflows/e2e.yml
e2e test workflow
This PR updates the version of the cypress browsers image in the e2e workflow.
=> chore(cypress): Update version of the cypress browsers image

locales/en.json, src/components/editor-page/editor-pane/editor-pane.tsx, src/components/editor-page/editor-pane/hooks/yjs/use-on-metadata-updated.ts, src/components/editor-page/editor-pane/hooks/yjs/use-on-note-deleted.ts
realtime communication hooks
This PR adds hooks for METADATA_UPDATED DOCUMENT_DELETED messages
=> feat: add hooks for METADATA_UPDATED DOCUMENT_DELETED messages

src/components/markdown-renderer/markdown-extension/highlighted-fence/hooks/use-code-dom.tsx
Code highlighter
This PR improves the code highlighter by using dompurify directly instead of constructing a markdown extension collection.
Not only is it less confusing this way, it also simplifies the workflow by sanitizing the html from hljs directly instead of using the parsing-dumping-sanitizing-parsing workflow that happens when using the sanitizer node preprocessor.
=> refactor(code highlighter): Use sanitizer directly

package.json
package.json
This PR fixes the dev:for-real-backend npm script. It now uses HD_EDITOR_BASE_URL instead of NEXT_PUBLIC_BACKEND_BASE_URL
=> refactor(package.json): fix dev:for-real-backend npm script

package.json, src/components/render-page/window-post-message-communicator/hooks/use-editor-receive-handler.ts, src/components/render-page/window-post-message-communicator/hooks/use-renderer-receive-handler.ts, src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts, yarn.lock
Window post message communicator
This PR replaces the custom single-handler architecture with eventemitter2.
=> feat(window post message communicator): Use EventEmitter2

src/components/editor-page/render-context/editor-to-renderer-communicator-context-provider.tsx, src/components/editor-page/render-context/renderer-to-editor-communicator-context-provider.tsx, src/components/editor-page/renderer-pane/hooks/use-force-render-page-url-on-iframe-load-callback.ts, src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
Window post message communicator
This PR adds uuids to identify and separate multiple renderers on one page
=> feat(window post message communicator): Add uuid to frames

package.json, yarn.lock
package.json
Adds a resolution to prevent multiple versions of the graphviz wasm lib.
=> chores(deps): Add resolution for @hpcc-js/wasm

locales/en.json, src/components/editor-page/sidebar/specific-sidebar-entries/export-menu-sidebar-menu.tsx, src/links.json
sidebar
This PR removes the pdf export sidebar entry.
The URL that is used in this entry doesn't exist anymore. We don't plan to implement pdf export with 2.0 anyway so this entry isn't needed.
=> fix(sidebar): Remove pdf export entry

.github/workflows/build.yml, .github/workflows/deploy-main.yml, .github/workflows/deploy-pr.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml
CI
This PR replaces deprecated commands in the CI configuration.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix(ci): Migrate setting of environment variables

renovate.json
renovate
This PR fixes the name of the node version regex manager
=> fix(ci): fix regex manager name for node version
